"""Concise visual-map wording. Full explanations remain in MAP_CONTENT/text versions.
Each numbered item corresponds to the same source panel; core concepts are retained.
"""
def p(title,*lines):return {'title':title,'lines':list(lines)}
COMPACT={
'00-cell-biology-overview':[
p('Cell structures','**Animal:** nucleus → DNA/control; cytoplasm → reactions; membrane → entry/exit.','**Mitochondria:** aerobic respiration. **Ribosomes:** make proteins.','**Plant/algal extras:** cellulose wall; permanent vacuole. Photosynthetic cells have chloroplasts.','**Bacteria:** smaller; no nucleus; DNA loop; some plasmids.'),
p('Specialised cells','**Sperm:** tail, mitochondria, acrosome enzymes. **Nerve:** long fibre, branches.','**Muscle:** contractile proteins, mitochondria. **Root hair:** large absorption area.','**Xylem:** hollow, lignified; water/minerals. **Phloem:** sugars; companion cells.'),
p('Differentiation & stem cells','**Differentiation:** becoming specialised; animals mainly early, plants throughout life.','**Embryonic:** most human cell types. **Bone marrow:** limited types. **Meristems:** any plant type.','Uses: tissue repair; plant clones. Weigh benefits, infection risk and ethical objections.'),
p('Microscopy','**Resolution:** distinguish nearby points. Electron microscopes give more detail and magnification.','**Magnification = image ÷ actual size.** Same units first: mm → µm ×1,000.','Practical: thin stained sample, angled coverslip; low power first; focus, draw, label and add a scale.'),
p('Culturing microorganisms','**Binary fission:** repeated doubling. Population = start × 2ⁿ; n = time ÷ division time.','**Asepsis:** sterilise, cool loop; tape edges, invert; school cultures **≤25°C**.','Compare antimicrobial discs; solvent control; repeat. **Zone area = πr²**; r = diameter ÷ 2.'),
p('Cell cycle','**Grow → copy DNA → mitosis → divide.**','Copies separate; nuclei, then cytoplasm/membrane divide. **Two identical cells; same chromosome number.**','For growth, development, repair and replacement.'),
p('Diffusion & exchange','**Diffusion:** net particles high → low; no respiration energy. Faster: steeper gradient, hotter, larger area.','Large organisms: **lower SA:V** → exchange/transport systems. Cube: SA = 6a²; V = a³.','Alveoli, villi, gills: large area, thin barrier, blood supply; gas exchange needs ventilation.'),
p('Osmosis & active transport','**Osmosis:** water, dilute → concentrated, through a partially permeable membrane.','Water gain: plant turgid; animal swells. Loss: plant flaccid; animal shrinks.','Practical: equal plant samples; weigh, soak, blot, reweigh. **% change = (final − initial) ÷ initial × 100.**','**Active transport:** low → high; respiration energy. Root minerals; gut sugars.')],
'01-cells':[
p('Animal cells','**Eukaryotic:** DNA enclosed in a nucleus.','**Nucleus:** genes control activities. **Cytoplasm:** enzyme-controlled reactions.','**Membrane:** controls entry/exit. **Mitochondria:** aerobic respiration transfers energy.','**Ribosomes:** protein synthesis.'),
p('Plant cells','Have all the animal-cell structures, plus:','**Cellulose wall:** strength/support; also in algae. **Permanent vacuole:** cell sap; water keeps the cell firm.','**Chloroplasts:** chlorophyll absorbs light for photosynthesis. Only in photosynthetic cells; normally absent from root hairs.'),
p('Bacterial cells','**Prokaryotic:** much smaller; no nucleus. Main DNA loop in cytoplasm; some have **plasmids** (extra genes).','Have membrane, cytoplasm, ribosomes and a **non-cellulose wall**. No mitochondria/chloroplasts.'),
p('Sperm cells','**Tail** → swimming. **Mitochondria** → energy for movement.','**Acrosome enzymes** → penetrate the egg’s outer layers.'),
p('Nerve & muscle cells','**Nerve:** long fibre carries impulses; branched ends connect cells.','**Muscle:** contractile proteins shorten the cell; mitochondria supply energy for contraction.'),
p('Root hair cells','Long extension → **large absorption area**. Water enters by **osmosis**.','Minerals enter by **active transport** when less concentrated in soil; mitochondria supply energy. Normally no chloroplasts underground.'),
p('Xylem & phloem','**Xylem:** dead, hollow tubes carry water/minerals; lignin strengthens walls against collapse.','**Phloem:** sieve tubes carry dissolved sugars; companion cells supply energy for loading.','Explain **feature → effect → function**, including in unfamiliar cells.'),
p('Differentiation','Developing specialised structures for a job. Animals: mainly **early in development**; plants: many cells **throughout life**.','Mature animal cell division mainly repairs/replaces cells. Differentiation is the process; specialisation is the result.')],
'02-cell-processes':[
p('Chromosomes & genes','Nucleus contains **DNA chromosomes**, each with many genes; normally paired in body cells.','After copying, each X is **one chromosome** with two joined identical copies (sister chromatids).'),
p('Grow & copy DNA','Before mitosis: cell grows; more ribosomes and mitochondria form.','DNA replicates. **DNA amount doubles; chromosome number does not.** Joined copies will separate.'),
p('Mitosis','Joined copies **separate**; one **complete set** moves to each end. The nucleus divides.','Copying happened **before** mitosis. Chromosome number is maintained, not halved.'),
p('Divide the cell','Cytoplasm and membrane divide → **two genetically identical daughter cells**, with the parent’s chromosome number.','For growth, development, repair/replacement, e.g. healing skin. Bacteria use **binary fission**, not mitosis.'),
p('Human stem cells','**Undifferentiated** cells divide and produce cells that differentiate.','**Embryonic:** most human types. **Adult bone marrow:** limited range, including blood cells. Source determines the range.'),
p('Medical uses','Potential replacement of insulin-producing cells in **diabetes**, or nerve cells in **paralysis**.','**Therapeutic cloning:** embryo has patient’s genes → matched tissue is not rejected by their immune system. Potential, not guaranteed cures.'),
p('Benefits, risks & ethics','Benefit: repair damaged tissue. Risks: **viral infection** and uncontrolled division.','Embryo destruction raises ethical/religious objections; others prioritise treatment benefits. Weigh source, benefits and risks; give a **reasoned judgement**.'),
p('Plant meristems','Can form **any plant cell type throughout life**. Produce clones quickly and economically.','Clone rare plants to prevent extinction; useful crops for features such as disease resistance. Plant cells come from plant meristems, not human stem cells.')],
'03-transport-processes':[
p('Diffusion','**Net movement:** gas/dissolved particles, high → low concentration, down the gradient.','Random movement; **no respiration energy**. Examples: O₂, CO₂; urea from cells into blood plasma. At equilibrium particles move, but no net movement.'),
p('Faster diffusion','**Steeper gradient:** greater net movement/second. **Hotter:** more kinetic energy.','**Larger area:** more particles cross. **Thinner barrier:** shorter diffusion path.'),
p('Osmosis','**Water:** dilute → concentrated solution through a **partially permeable membrane**.','Dilute side has more water relative to solute. Water crosses; some solutes cannot. No respiration energy. Movement is both ways; arrows show the net direction.'),
p('Water gain or loss','Dilute outside → water enters. Plant: vacuole fills, **turgid**; wall prevents bursting. Animal: may swell/burst.','Concentrated outside → water leaves. Plant: **flaccid**; severe loss → plasmolysis (membrane pulls from wall). Animal: shrinks.'),
p('Active transport','Substances move **low → high**, against the gradient, via membrane proteins.','Needs **energy from respiration**, like moving uphill. Diffusion/osmosis move down gradients; only osmosis is water-only.'),
p('Where it helps','**Roots:** take up minerals for growth even when soil concentration is lower.','**Gut:** absorbs sugars into blood even when blood concentration is higher; sugars fuel respiration. Many mitochondria support high energy demand.'),
p('Osmosis practical','Vary salt/sugar concentration; use equal-size potato cylinders. Weigh initially; equal solution volumes, including distilled water.','Control tissue source, size, time and temperature. **Blot consistently**, reweigh; repeat and calculate means. Blotting removes surface liquid; cut safely.'),
p('Calculate & interpret','**% change = (final − initial) ÷ initial × 100.** 2.50 → 2.20 g: −0.30 ÷ 2.50 × 100 = **−12%**.','Gain +; loss −. Plot concentration (x), mean % change (y). Best-fit curve’s 0% crossing = **no net movement**, not no movement.','Rate = change ÷ time: 0.12 g ÷ 30 min = **0.004 g/min**. Check anomalies; repeat/test nearer zero.')],
'04-exchange-surfaces':[
p('Why exchange systems?','Single cells: **large SA:V**; their outer surface can meet exchange needs.','Large multicellular organisms: **lower SA:V**, long diffusion distances → specialised exchange surfaces and transport systems.'),
p('Surface area : volume','Cube side a: **SA = 6a²; V = a³.**','1 cm cube: 6 ÷ 1 = **6:1**. 3 cm cube: 54 ÷ 27 = **2:1**. Larger cube: more total area, less area per unit volume.','Cutting into pieces exposes more area without changing total volume.'),
p('Lung alveoli','Many tiny air sacs → large area; thin alveolar/capillary walls → short path.','Blood supply and ventilation maintain steep gradients. **O₂: air → blood. CO₂: blood → air.** An alveolus is one air sac, not a lung.'),
p('Small intestine','**Villi/microvilli:** large area. Thin lining: short diffusion distance.','Blood removes absorbed substances, maintaining gradients. Sugars can enter blood by **active transport** against a gradient.'),
p('Fish gills','Many **filaments/lamellae** → large area; thin surfaces → short diffusion distance.','Blood carries substances to/from the surface; flowing water maintains gradients. **O₂: water → blood; CO₂ moves out.**'),
p('Plant roots','**Root hairs:** large contact area with soil. Water enters by **osmosis** through a partially permeable membrane.','Minerals can enter against the gradient by **active transport**, using respiration energy.'),
p('Plant leaves','Broad → large area. Thin → short diffusion distance. **Stomata** let gases in/out; internal **air spaces** shorten paths.','For photosynthesis: CO₂ enters, O₂ can diffuse out. State substance and direction in context.'),
p('Explain the adaptation','**Large area:** more particles cross at once. **Thin barrier:** shorter diffusion path.','**Blood supply:** brings/removes substances to maintain gradients. **Ventilation:** refreshes air/water.','Link **adaptation → effect → faster exchange**.')],
'05-microscopy':[
p('Magnification & resolution','**Magnification:** how much larger the image is. **Resolution:** distinguish two nearby points as separate.','A blurry photo can be enlarged without adding detail. Bigger does not mean clearer.'),
p('Light & electron','Light microscopes show cells and visible structures.','Electron microscopes have much greater **magnification and resolving power** → reveal finer sub-cellular detail. Better resolution separates nearby details.'),
p('Size formulae','**Magnification = image ÷ actual size.**','Actual = image ÷ magnification. Image = actual × magnification.','Use **the same units** before dividing. Magnification has no unit; sizes do.'),
p('Worked magnification','Image 30 mm; actual 60 µm. **30 × 1,000 = 30,000 µm.**','30,000 ÷ 60 = **×500**. Microscope total = eyepiece × objective: ×10 × ×40 = **×400**.','Drawing magnification depends on drawing size, not automatically the microscope setting.'),
p('Units & standard form','**1 cm = 10 mm; 1 mm = 1,000 µm; 1 µm = 1,000 nm.**','1 µm = 10⁻⁶ m; 1 nm = 10⁻⁹ m. Large → small units: multiply; reverse: divide.','a × 10ⁿ, **1 ≤ a < 10**. Example: 0.000060 m = **6.0 × 10⁻⁵ m**.'),
p('Scale & area','20 µm ÷ 2 µm = 10: **one order of magnitude**. Convert units before comparing.','Scale bar = actual distance; compare image length with it. Estimate relative sizes/areas when boundaries are unclear.','For similar shapes, length ×2 → **area ×4**; state this assumption.'),
p('Prepare the slide','Observe **plant and animal cells**. Thin onion epidermis + water; suitable stain (e.g. iodine) improves contrast.','Lower coverslip **at an angle** to reduce bubbles. Thin tissue lets light through and avoids overlap.','Use prepared animal cells or samples approved by your teacher. Handle glass, stains and samples safely.'),
p('Focus & draw','Lowest-power objective; **coarse then fine focus**. Centre cells; increase magnification; use fine focus.','Draw clear pencil outlines, no shading. Label identifiable structures; add **magnification scale or scale bar**. Interpret visible features, not memory alone.')],
'06-culturing-microorganisms':[
p('Binary fission','One bacterial cell → two. With nutrients and suitable temperature, division may take **20 minutes**; use the given time.','**1 → 2 → 4 → 8:** repeated doubling, not addition. No nucleus; bacteria do not use mitosis.'),
p('Growing a culture','**Broth:** nutrients for growth. **Agar:** surface for colonies (a visible group from an initial cell/group).','Uncontaminated cultures allow fair antimicrobial comparisons. **Aseptic technique** keeps unwanted microorganisms out.'),
p('Sterile equipment','Sterilise dishes/medium to remove unwanted microbes. **Flame the loop; cool it** so it does not kill the culture.','Open lid briefly to limit airborne contamination. Follow school handling/disposal procedures.'),
p('Safe incubation','**Tape edges, not a full seal:** prevents opening; allows gas exchange.','**Invert:** condensation cannot drip onto culture. **Maximum 25°C** in school limits harmful human pathogens. Do not open incubated plates.'),
p('Antimicrobial discs','Use asepsis to prepare a lawn on sterile agar. Add **antibiotic/antiseptic discs** and a **solvent-only control**.','Incubate safely; measure inhibition zones. Repeat and calculate a mean for each substance.'),
p('Variables & conclusions','Change: substance/type or concentration. Measure: **zone diameter or area**.','Keep strain, agar, disc size, substance volume, time and temperature constant.','Larger zone → more inhibition **under these conditions**. Different diffusion rates mean this does not prove effectiveness inside a patient.'),
p('Zone area','**Radius = diameter ÷ 2; area = πr².**','Diameter 12 mm → radius 6 mm → π × 6² = **113 mm²** (3 s.f.).','Use squared units. Subtract disc area only if asked. A clear zone means **growth was inhibited**.'),
p('Repeated doubling','**n = total time ÷ division time.** Final population = **start × 2ⁿ**.','50 bacteria; 20-minute divisions; 2 h: 120 ÷ 20 = 6 doublings.','50 × 2⁶ = **3,200 = 3.2 × 10³**. Keep time units consistent; apply the stated growth conditions.')]
}
