"""Reusable course-map definitions; each panel has concise student-facing content."""
def p(title,*lines):return {'title':title,'lines':list(lines)}
def m(slug,title,labels,panels,pics=None):return {'slug':slug,'title':title,'labels':labels,'panels':panels,'pics':pics or {}}
MAPS={'02 - Organisation':[
 m('00-organisation-overview','Organisation overview',['Break down food','Transport & protect','Plant systems'],[
 p('Organisation & digestion','**Cells → tissues → organs → systems.**','Digestion: large insoluble molecules → small soluble molecules; absorption into blood.'),
 p('Enzymes & tests','Amylase → sugars; protease → amino acids; lipase → glycerol/fatty acids.','Bile neutralises acid and emulsifies fat. Enzymes have specific active sites.','Food tests identify nutrients; pH investigation uses iodine and **rate = 1/time**.'),
 p('Heart, blood & lungs','**Right heart → lungs; left heart → body.** Valves prevent backflow.','Arteries leave; veins return; capillaries exchange. Red cells carry O₂; white cells defend; platelets clot.','Alveoli: large area, thin barrier; blood/ventilation maintain gradients.'),
 p('Health & disease','Coronary deposits reduce oxygen supply; stents open arteries, statins lower cholesterol.','Risk factors raise probability. Correlation alone is not causation.','Benign tumours stay local; malignant cells invade/spread.'),
 p('Leaf structure','Palisade chloroplasts absorb light; spongy air spaces allow diffusion.','Epidermis/cuticle protect; guard cells control stomata. Meristems divide at growing tips.'),
 p('Transport in plants','Root hairs: water by osmosis, minerals by active transport.','Xylem carries water/minerals; phloem translocates sugars.','Transpiration rises with heat/wind/light, falls with humidity. Potometers measure uptake.')],{2:('course-heart',95)}),
 m('01-digestion-and-enzymes','Digestion & enzymes',['Food → molecules','How enzymes work','Investigate'],[
 p('The digestive route','Mouth: chewing/amylase. Oesophagus: moves food. Stomach: acid, protease and mixing.','Pancreas supplies enzymes; small intestine digests/absorbs; large intestine absorbs water.','**Egestion:** undigested food out. **Excretion:** metabolic waste out.'),
 p('Enzyme products','Amylase: **starch → sugars**; made in salivary glands, pancreas and small intestine.','Protease: **protein → amino acids**; stomach, pancreas, small intestine.','Lipase: **lipid → glycerol + fatty acids**; pancreas and small intestine.'),
 p('Specific active sites','Enzymes are reusable **protein catalysts**. Substrate binds a complementary active site.','Warming increases collisions to an optimum; excess heat/extreme pH can **denature** the active site. Cold slows activity.'),
 p('Bile & absorbed products','Liver makes bile; gall bladder stores it. **Alkaline** bile neutralises stomach acid.','Emulsification makes fat droplets → more surface area for lipase. Bile is not an enzyme.','Products build new molecules; glucose can be respired.'),
 p('Food tests','Benedict’s + water bath: reducing sugar → coloured precipitate. Iodine: starch → blue-black.','Biuret: protein → purple. Sudan III: lipid → red oil layer.','Separate samples; positive/negative controls; goggles and safe heating.'),
 p('Amylase & pH practical','Vary buffer pH; control temperature, concentrations and volumes.','Sample onto fresh iodine every **30 s**. Endpoint: iodine stays orange-brown. Repeat.','Same starch amount: **relative rate = 1/time**. Shorter intervals improve endpoint resolution.')],{2:('course-enzyme',95)}),
 m('02-circulation-and-health','Circulation & health',['Move blood','Exchange & defend','Evaluate disease'],[
 p('Double circulation','Body → vena cava → right atrium/ventricle → pulmonary artery → lungs.','Lungs → pulmonary vein → left atrium/ventricle → aorta → body.','Left ventricle thicker; valves prevent backflow; coronary arteries supply heart muscle.'),
 p('Heart rate & flow','Pacemaker cells in right atrium set the rhythm; artificial pacemakers correct irregularities.','**Output = rate × stroke volume.** 70 × 75 = 5,250 cm³/min = 5.25 dm³/min.'),
 p('Vessels & lungs','Arteries: thick elastic/muscular walls for high pressure. Veins: wide lumen and valves.','Capillaries: one-cell-thick walls. Alveoli: large area, short path, blood/ventilation maintain gradients.','**O₂: alveoli → blood; CO₂: reverse.**'),
 p('Blood components','Red cells: haemoglobin, biconcave shape, no nucleus → O₂ transport.','White cells: phagocytosis, antibodies/antitoxins. Platelets: clotting.','Plasma carries cells, nutrients, hormones, CO₂ and urea; distributes heat.'),
 p('Disease & treatment','Fat narrows coronary arteries → less O₂/respiration. Stent opens; statin lowers cholesterol.','Faulty valves leak/restrict flow. Compare valve replacement, donor and artificial hearts: benefit, surgery, clot/rejection risks.'),
 p('Health & cancer','Health = physical/mental well-being; diseases interact. Lifestyle/environment/genetics affect risk.','Cancer: uncontrolled division. **Benign:** local; **malignant:** invasion/secondary tumours.','Correlation alone ≠ causation. Compare representative rates and social/financial costs.')],{2:('alveolus',95)}),
 m('03-plant-tissues-and-transport','Plant tissues & transport',['Structure → function','Move substances','Measure water loss'],[
 p('Leaf tissues','Epidermis/cuticle protect and limit evaporation. Palisade cells absorb light using chloroplasts.','Spongy mesophyll air spaces shorten gas paths. Guard cells control stomata.'),
 p('Roots & growing tips','Root hairs increase surface area: water enters by **osmosis**, minerals by **active transport**.','Meristems at root/shoot tips contain dividing cells that differentiate.'),
 p('Xylem & phloem','**Xylem:** dead hollow tubes, lignin support; root → leaf water/minerals.','**Phloem:** living elongated cells with end-wall pores; dissolved sugars move by **translocation** to growing/storage tissues.'),
 p('Transpiration','Water evaporates from mesophyll; vapour diffuses out through stomata.','Water loss helps pull a continuous stream up xylem. Guard cells balance gas exchange and water loss.'),
 p('Changing the rate','Heat → faster evaporation/diffusion. Wind removes humid air → steeper gradient.','Humidity → smaller gradient, slower loss. Light usually opens stomata, increasing loss if water is available.'),
 p('Potometers & sampling','Cut shoot under water; airtight setup; dry leaves; acclimatise. Change one factor, control others; repeat.','Measures **uptake**, not exact loss. Rate = distance/time; volume = **πr² × distance**.','Count stomata in several random measured areas; report mean number per area.')],{0:('leaf',85)})
]}
MAPS['03 - Infection and response']=[
 m('00-infection-and-response-overview','Infection and response overview',['Cause & spread','Protect & treat','Plant health'],[
 p('Pathogens cause disease','Bacteria may release toxins; viruses reproduce inside cells. Fungi and protists also cause disease.','Spread: contact, water, air, food or vectors. Hygiene, isolation, vaccination and vector control break routes.'),
 p('Named human infections','Measles: droplets, fever/rash. HIV: body fluids, damages immune cells; antiretrovirals control it.','Salmonella: food, gut illness. Gonorrhoea: sexual contact, discharge/pain; antibiotic resistance matters.','Malaria: protist carried by mosquitoes; recurrent fever. Nets and breeding control reduce spread.'),
 p('Defence & vaccination','Skin, mucus/cilia and stomach acid form barriers. White cells engulf pathogens, make antibodies and antitoxins.','Vaccination → specific antibodies/memory → faster later response. High uptake reduces transmission.'),
 p('Medicines & targeting','Antibiotics treat bacteria, not viruses. Painkillers treat symptoms. Trials check toxicity, efficacy and dose.','Monoclonals: lymphocyte + tumour cell → hybridoma → clone. Specific binding enables tests and targeted treatments; side effects remain.'),
 p('Plant problems','TMV: mosaic leaves; black spot: fungal spots/leaf loss. Both reduce photosynthesis. Aphids feed on sap.','Nitrate shortage → less protein/growth; magnesium shortage → less chlorophyll/chlorosis.','Identify using symptoms, references, labs or antibody tests.'),
 p('Plant protection','Cell walls, waxy cuticle and shedding bark resist entry.','Antibacterial chemicals attack bacteria; poisons, thorns and hairs deter feeding.','Drooping/curling leaves and mimicry discourage herbivores.')],{2:('course-memory',120)}),
 m('01-pathogens-and-disease','Pathogens & disease',['How infection spreads','Viral infections','Other pathogens'],[
 p('Four pathogen groups','**Bacteria:** cells multiply and may release toxins. **Viruses:** reproduce inside living cells, damaging them.','**Fungi** and **protists** can cause disease too. Communicable diseases pass between organisms.'),
 p('Break the transmission route','Contact → hygiene/isolation. Contaminated water/food → sanitation, clean preparation and cooking.','Airborne droplets → reduce exposure/isolate infected people. Vectors → prevent bites and breeding.','Vaccination reduces susceptible hosts; match prevention to the pathogen’s route.'),
 p('Measles','Virus spread by **inhaling droplets** from coughs/sneezes.','**Fever and red rash**; complications can be fatal.','Vaccination in childhood reduces illness and spread.'),
 p('HIV → immune damage','Spread by **sexual contact or exchanged body fluids**, including shared needles. Initially flu-like illness.','Attacks immune cells; **AIDS** is severe late-stage damage, with vulnerability to infections/cancers.','Antiretroviral drugs control multiplication. Condoms and avoiding needle sharing reduce spread.'),
 p('Bacterial infections','**Salmonella:** contaminated food; bacteria/toxins cause fever, cramps, vomiting and diarrhoea. Hygiene/cooking and poultry vaccination help.','**Gonorrhoea:** sexual contact; yellow/green discharge and painful urination. Condoms and suitable antibiotics help; resistant strains limit treatment.'),
 p('Malaria','A **protist** causes recurrent fever and can be fatal. The mosquito is the **vector**, not the pathogen.','Life cycle includes mosquitoes. Nets prevent bites; controlling breeding reduces vectors.','Plant virus/fungus examples: **TMV** and **rose black spot**; see plant-health map.')]),
 m('02-defence-and-vaccination','Defence & vaccination',['Keep pathogens out','Respond inside','Remember & protect'],[
 p('Skin & nose','**Skin:** physical barrier; antimicrobial substances and clotting at cuts help protect.','**Nose:** hairs and mucus trap pathogens and particles.','These barriers are **non-specific**: they act against many pathogens.'),
 p('Airways & stomach','Trachea/bronchi: **mucus traps pathogens**; **cilia move mucus to the throat** for swallowing.','Stomach **hydrochloric acid** kills many swallowed pathogens.'),
 p('White blood cells','**Phagocytosis:** engulf and digest pathogens.','**Antibodies:** bind specific pathogen antigens and help destroy the pathogen.','**Antitoxins:** neutralise bacterial toxins. Different white cells have different roles.'),
 p('Specificity','An antibody’s binding site has a shape **complementary to its antigen**.','Antibodies target antigens; antitoxins neutralise toxins. They are not interchangeable terms.'),
 p('Vaccination sequence','Dead/inactive pathogen or antigens → white cells make specific antibodies → memory cells remain.','Later exposure → **faster, larger antibody response**, destroying pathogens before significant illness.'),
 p('Population protection','High vaccine uptake leaves fewer susceptible hosts, reducing transmission and helping protect those unable to be vaccinated.','Evaluate disease reduction against reliable risk evidence, cost, access and uptake. Protection is not identical for every person.')],{4:('course-memory',120)}),
 m('03-medicines-and-antibodies','Medicines & antibodies',['Treat disease','Test new drugs','Target one antigen'],[
 p('Antibiotics & symptoms','Antibiotics such as penicillin treat bacteria; choose an effective one. **Resistance** makes infections harder to treat.','Antibiotics do not kill viruses. Viruses reproduce inside cells, making safe targeting difficult.','Painkillers relieve symptoms without killing pathogens.'),
 p('Drug origins','**Digitalis ← foxglove. Aspirin ← willow.**','**Penicillin:** Fleming’s discovery from Penicillium mould.','Most new drugs are synthesised; natural chemicals may provide starting points.'),
 p('Testing sequence','Check **toxicity, efficacy and dose**. Preclinical: cells, tissues, live animals.','Clinical: low doses in healthy volunteers, then patients to test effectiveness and optimum dose.','Results undergo **peer review** before publication.'),
 p('Fair comparisons','Placebo: no active drug. **Double-blind:** patients and assessors do not know allocations.','Random allocation, comparable groups and large samples reduce misleading effects.','Compare recovery rates and side effects, not raw counts alone.'),
 p('Make monoclonal antibodies','Antigen stimulates mouse lymphocytes. Fuse an antibody-producing lymphocyte with a tumour cell → **hybridoma**.','Select and clone one hybridoma; collect/purify antibodies. Clone makes antibodies with **one specific binding site**.'),
 p('Uses & limits','Specific binding: pregnancy tests, hormone measurement, pathogen detection; fluorescent tags locate molecules.','Attach toxic drugs/radioactive substances/growth blockers to target cancer cells.','Targeting reduces unwanted damage but side effects and unsuitable targets can limit benefit.')],{4:('course-hybridoma',90)}),
 m('04-plant-health','Plant health',['Recognise causes','Identify & explain','Resist attack'],[
 p('Plant infections','**TMV:** virus; mosaic leaf discolouration → less photosynthesis/growth. Limit transfer from infected plants/tools.','**Rose black spot:** fungus; purple/black spots, yellow leaves, early leaf fall → less photosynthesis. Wind/water spread spores; remove affected leaves or use fungicides.'),
 p('Pests & symptoms','**Aphids** feed on sugar-rich sap, reducing growth; may transmit viruses.','Look for stunted growth, spots, decay, growths, malformed stems/leaves, discolouration and pests.','A symptom alone may have several possible causes.'),
 p('Mineral deficiencies','**Nitrate:** needed for amino acids/proteins. Shortage → stunted growth.','**Magnesium:** needed for chlorophyll. Shortage → **chlorosis** and reduced photosynthesis.','Deficiencies are not communicable; mineral supply will not cure a virus.'),
 p('Identify the problem','Compare symptoms with reliable gardening references.','Laboratories identify pathogens; **monoclonal-antibody kits** test for specific targets.','Combine evidence; a negative test for one pathogen does not rule out other causes.'),
 p('Physical & chemical','**Cellulose cell walls**, tough waxy cuticle and dead bark resist entry. Shedding bark can remove pathogens.','Antibacterial chemicals act against bacteria. **Poisons deter herbivores**.'),
 p('Mechanical adaptations','**Thorns and hairs** deter feeding.','Leaves may **droop or curl** when touched.','**Mimicry** tricks animals into avoiding plants. Link each feature to how it protects.')],{2:('course-chlorosis',85)})]
MAPS['04 - Bioenergetics']=[
 m('00-bioenergetics-overview','Bioenergetics overview',['Store light energy','Control & measure','Release & use energy'],[
 p('Photosynthesis','**Carbon dioxide + water → glucose + oxygen.** Light transfers energy to chloroplasts; chlorophyll absorbs it.','**Endothermic:** energy is taken in. Plants respire all the time; photosynthesis needs light.'),
 p('Use the glucose','Respiration; starch and fat/oil storage; cellulose cell walls.','Glucose plus nitrate-derived nitrogen → amino acids → proteins.'),
 p('Limiting factors','Light, CO₂, temperature and chlorophyll can limit rate. A plateau means extra light alone will not help.','**Intensity ∝ 1/distance²**; doubling distance quarters intensity.','Greenhouses: balance extra crop income against heat/light/CO₂ costs.'),
 p('Pondweed practical','Change lamp distance; measure oxygen volume/time. Control temperature, CO₂ supply, plant and background light.','Acclimatise; repeat; calculate mean. Bubbles vary in size, so volume is usually better.','Rate = volume/time; plot against light intensity or 1/distance².'),
 p('Respiration pathways','**Aerobic:** glucose + O₂ → CO₂ + water; more energy transferred.','**Anaerobic:** muscles → lactic acid; yeast/plants → ethanol + CO₂. Less energy per glucose.','Respiration is exothermic and continuous; fermentation makes bread rise and produces alcohol.'),
 p('Exercise & metabolism','Exercise raises heart rate, breathing rate/volume. Oxygen shortage → more anaerobic respiration and fatigue.','Oxygen debt: extra oxygen needed afterwards. Blood takes lactic acid to liver → glucose.','Metabolism = all cell/body reactions; builds carbohydrates, lipids and proteins; excess nitrogen → urea.')],{2:('course-light',100)}),
 m('01-photosynthesis-and-limiting-factors','Photosynthesis & limiting factors',['Make & use glucose','Explain rate changes','Apply the maths'],[
 p('The reaction','**6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂**','Chlorophyll absorbs light; energy transfers from the environment to chloroplasts. **Endothermic.**','CO₂ enters stomata; roots/xylem supply water. Light is energy, not a material reactant.'),
 p('Glucose pathways','Respiration releases energy; starch and fats/oils store resources. Cellulose strengthens cell walls.','Glucose and **nitrate ions** supply materials for amino acids → proteins.'),
 p('Four interacting factors','More light or CO₂ raises rate only while that factor limits it.','Warming towards optimum raises enzyme activity; excess heat can **denature enzymes**.','Less chlorophyll → less light absorption. Magnesium deficiency or disease can reduce chlorophyll.'),
 p('Interpret the plateau','Rising rate with light → light is limiting. Plateau → another factor limits rate.','Compare curves at the same other conditions: if added CO₂ raises rate, CO₂ had limited it.','A plateau alone does not identify which factor limits rate.'),
 p('Inverse-square law','**Intensity ∝ 1/distance².** I₂/I₁ = (d₁/d₂)².','20 → 40 cm: intensity becomes **¼**. 30 → 15 cm: becomes **4×**.','Use consistent units. Photosynthesis rate need not change by the same factor.'),
 p('Greenhouse decisions','Adding heat, light or CO₂ costs money. Improve the actual limiting factor.','Extra profit = extra crop income − extra cost. £240 − £170 = **£70**.','Highest photosynthesis rate is not always the most profitable setting.')],{3:('course-rate',130)}),
 m('02-photosynthesis-practical','Photosynthesis practical',['Set up fairly','Measure & calculate','Evaluate evidence'],[
 p('Choose the variables','Independent: lamp distance/light intensity. Dependent: **oxygen production rate**.','Pondweed in sodium hydrogencarbonate solution; keep CO₂ supply, volume, plant and orientation constant.'),
 p('Control temperature','Use a water bath/heat shield and check with a thermometer. The lamp can heat the water.','Keep background light steady. Use the same measurement period; avoid spills near electrics and hot-lamp burns.'),
 p('Collect the data','Measure source-to-plant distance; allow the plant to **acclimatise**.','Collect oxygen volume over a set time using an inverted water-filled tube, or count bubbles.','Repeat at several distances; repeat each condition and calculate a mean. Investigate anomalies.'),
 p('Calculate rate','**Rate = gas volume/time.** 3.6 cm³ in 4 min = **0.90 cm³/min**.','Bubble estimate: 48 in 2 min = **24 bubbles/min**.','Keep time/volume units consistent. More gas in a longer time is not necessarily a faster rate.'),
 p('Plot & explain','Plot rate on y-axis; intensity or **1/distance²** on x-axis. Label units and use a suitable scale/best-fit curve.','Closer lamp → greater intensity; rate rises while light limits it. Another limiting factor can cause a plateau.'),
 p('Limits & improvements','Unequal bubble sizes → count is approximate; measure **gas volume** instead.','Some oxygen dissolves or is used in respiration; check collector for gas leaks.','Repeats reduce random uncertainty; they do not fix heating, leaks or another uncontrolled variable.')],{0:('course-light',100)}),
 m('03-respiration-exercise-and-metabolism','Respiration, exercise & metabolism',['Transfer energy','Respond to demand','Build & break molecules'],[
 p('Aerobic respiration','**Glucose + oxygen → CO₂ + water.** Mostly in mitochondria; complete oxidation.','Exothermic, continuous in living cells; energy for movement, keeping warm and building molecules.','Respiration is not breathing; energy is transferred, not created.'),
 p('Anaerobic & fermentation','Muscles: **glucose → lactic acid**. Yeast/plants: **glucose → ethanol + CO₂**. No oxygen required.','Incomplete breakdown transfers much less energy per glucose than aerobic respiration.','Yeast fermentation: CO₂ raises bread dough; ethanol makes alcoholic drinks.'),
 p('During exercise','Heart rate and breathing rate/volume increase, delivering more oxygenated blood to muscles.','If oxygen supply cannot meet demand, anaerobic respiration increases → lactic acid builds up.','Prolonged vigorous activity → fatigue and less efficient contraction.'),
 p('Recovery & investigation','**Oxygen debt:** extra oxygen needed after exercise to deal with accumulated lactic acid. Blood carries it to liver → glucose.','Compare resting/post-exercise pulse; standardise time/pace, allow recovery, repeat and use safe activities.','15-second pulse count × 4 = beats/min.'),
 p('Building molecules','**Metabolism = all reactions** in cells/body. Enzymes control reactions; respiration supplies energy.','Glucose → starch (plants), glycogen (animals), cellulose (plant walls).','**1 glycerol + 3 fatty acids → lipid.**'),
 p('Protein & waste','Plants: glucose + nitrate-derived nitrogen → amino acids → proteins.','Excess proteins/amino acids are broken down, producing **urea for excretion**.','Digestion supplies small molecules; cells rebuild their own materials. Respiration is one part of metabolism.')])]
