from biology_course_maps import p,m
MAPS={1:[
m('00-atomic-structure-overview','Atomic structure overview',['Describe matter','Explain atoms','Predict properties'],[
p('Elements, compounds, mixtures','Element: one proton number. Compound: elements chemically joined in fixed proportions. Mixture: not chemically joined.','Balance equations with coefficients, never by changing formulae.'),
p('Separate physically','Insoluble solid → filtration. Dissolved solid → crystallisation. Solvent → simple distillation.','Miscible liquids → fractional distillation. Dyes → chromatography; pencil baseline above solvent.'),
p('Particles & isotopes','Proton +1, neutron 0, electron −1. Atomic number = protons; mass number = protons + neutrons.','Neutral atoms: protons = electrons. Ions gain/lose electrons. Isotopes differ in neutrons.','Aᵣ = sum(mass × % abundance)/100.'),
p('Electrons & models','First 20: shells fill 2,8,8,2. Same main group → same outer electrons; period → occupied shells.','Scattering evidence → tiny positive nucleus, mostly empty space. Bohr: shells; Chadwick: neutrons.'),
p('Group patterns','Group 0: full outer shell, unreactive; boiling point rises down group.','Group 1: loses 1 electron; reactivity rises down group. Group 7: gains 1; reactivity falls.','More reactive halogen displaces less reactive halide.'),
p('Table & transition metals','Mendeleev left gaps and predicted properties; modern order is proton number.','Transition metals: generally denser, stronger, harder, higher melting and less reactive than Group 1.','Many form coloured compounds, variable-charge ions and catalysts.')]),
m('01-atoms-isotopes-and-models','Atoms, isotopes & models',['Count particles','Arrange electrons','Follow the evidence'],[
p('Nucleus & charge','Protons +1 and neutrons 0 each have relative mass 1. Electrons −1 have tiny mass.','Atomic number = protons. Neutrons = mass number − atomic number.','Na-23: 11p, 12n, 11e. Na⁺: 11p, 12n, 10e.'),
p('Size & isotope averages','Atom radius ≈ 10⁻¹⁰ m; nucleus ≈ 10⁻¹⁴ m or less. Almost all mass is nuclear. **1 nm = 10⁻⁹ m.**','Isotopes: same protons, different neutrons. Aᵣ weights each isotope by abundance.','75% mass 35 + 25% mass 37 → **35.5**.'),
p('Shells & position','Lowest shells fill first: **2,8,8,2** for first 20 elements. O: 2,6; Na: 2,8,1; Ca: 2,8,8,2.','Period = occupied shells. Same main group = same outer electrons → similar reactions.','Metals generally lose electrons; non-metals gain/share.'),
p('Atoms → ions','Losing negative electrons produces a **positive ion**; gaining them produces a negative ion.','The number of protons stays unchanged: it remains the same element.','Full outer shells help explain the stability of noble gases.'),
p('Scattering conclusions','Most alpha particles pass → atom mostly empty space.','Some deflect → nucleus is positive and repels positive alpha particles.','Very few return → tiny, dense nucleus holds most mass; contradicts spread-out positive charge.'),
p('Changing models','Indivisible spheres → discovery of electron → plum pudding. Scattering → nuclear model.','Bohr: specific electron shells. Later work: protons. Chadwick: neutrons.','New experimental evidence can replace a scientific model.')],{3:('chem-ion',95)}),
m('02-substances-and-separation','Substances & separation',['Identify & represent','Separate solids','Separate liquids'],[
p('What is the substance?','Element: atoms of one element. Compound: different elements chemically combined in a fixed ratio.','Mixture: substances retain chemical properties and can be separated physically. Compounds need chemical reactions.'),
p('Symbols & equations','H₂O = 2H and 1O; Ca(OH)₂ = 1Ca, 2O, 2H. Use correct upper/lower case in symbols.','**2Mg + O₂ → 2MgO.** Count each element on both sides; change coefficients only.','Binary names often end -ide; -ate names usually include oxygen.'),
p('Filtration','Separates **insoluble solid** from liquid. Residue stays on filter; filtrate passes through.','Dissolved salt passes through too. Salt + sand: dissolve salt, filter sand, crystallise filtrate.'),
p('Crystallisation','Partly evaporate solvent → concentrated solution → cool → crystals form.','Filter crystals and dry them. Avoid heating hydrated salts strongly to complete dryness.','Wear goggles; handle hot glassware carefully.'),
p('Distillation','Simple: boil liquid, cool vapour in condenser, collect liquid distillate. Recover water from salt solution.','Fractional: column gives repeated evaporation/condensation to separate miscible liquids by boiling point.','Lower-boiling fraction usually comes first; cooling water enters condenser at bottom.'),
p('Chromatography','Components have different attractions to solvent and stationary phase, so travel different distances.','Pencil baseline **above solvent**; small spots; mark solvent front. Ink could dissolve; submerged spots wash off.','No new substances form in these physical separations.')]),
m('03-periodic-patterns','Periodic patterns',['Arrange & explain','Compare the groups','Apply predictions'],[
p('Modern & historical tables','Modern order: **atomic number**. Groups link outer electrons and reactions; periods link occupied shells.','Mendeleev used mass/properties, left gaps and predicted missing elements. Discoveries supported predictions; isotopes explain mass-order anomalies.'),
p('Group 0','Full outer shell: 8 electrons except **helium has 2**. Very unreactive, monatomic gases.','Boiling point increases with atomic mass down the group. Use the trend to predict values.'),
p('Group 1','One outer electron → **+1 ions**. Li, Na, K: water → hydroxide + H₂; oxygen → oxides; chlorine → chlorides.','**2Na + 2H₂O → 2NaOH + H₂.** Alkaline solution; reactions get more vigorous Li → Na → K.','Down group: more distance/shielding → outer electron lost more easily → reactivity rises.'),
p('Group 7','Seven outer electrons; gain one → **−1 ions**. Diatomic Cl₂, Br₂, I₂. Metal halides ionic; non-metal compounds covalent.','Cl₂ green gas; Br₂ red-brown liquid; I₂ grey-black solid. Melting/boiling points rise down group.','More distance/shielding → weaker attraction for incoming electron → reactivity falls.'),
p('Halogen displacement','More reactive halogen displaces less reactive halogen from its aqueous salt.','**Cl₂ + 2KBr → 2KCl + Br₂.** Ionic: Cl₂ + 2Br⁻ → 2Cl⁻ + Br₂.','Iodine cannot displace chlorine from chloride. Use group position to predict.'),
p('Transition metals','Cr, Mn, Fe, Co, Ni, Cu: generally stronger/harder/denser, higher melting and less reactive than Group 1.','Many have variable ion charges, coloured compounds and catalytic uses.','Fe²⁺/Fe³⁺; blue copper sulfate; iron/nickel catalysts. Trends have exceptions.')]) ]}

MAPS[2]=[
m('00-bonding-overview','Bonding & properties',['Bond particles','Explain behaviour','Choose materials'],[
p('Three strong bonds','Ionic: attraction between opposite ions after electron transfer. Covalent: shared electron pairs attract both nuclei.','Metallic: positive ions attract delocalised electrons. Identify the charged particles in explanations.'),
p('Structure decides properties','Ionic lattices: high melting; conduct only molten or dissolved, when ions move.','Small molecules: low melting/boiling; weak forces between molecules. No mobile charged particles.','Giant covalent: many strong bonds → high melting.'),
p('States & models','Solid: particles vibrate in fixed positions. Liquid: close particles move past each other. Gas: particles far apart, moving randomly.','At a change of state, energy changes attractions/spacing, not particle identity. Model drawings simplify size, forces and movement.'),
p('Metals & polymers','Metals conduct through mobile delocalised electrons; layers can slide. Different-sized alloy atoms hinder sliding.','Polymers: long molecules, strong bonds along each chain, forces between chains; most are solid at room temperature.'),
p('Carbon structures','Diamond: four bonds per carbon, rigid and hard, no free electrons. Graphite: three bonds; weak forces between layers let them slide.','Graphene: one strong, conducting layer. Fullerenes: hollow cages; nanotubes: strong conducting cylinders.'),
p('Nanoparticles','1–100 nm: large surface area : volume ratio. Small amounts can be effective catalysts or coatings.','Uses include medicine, electronics, sunscreen and antibacterial surfaces. Properties differ from bulk material; assess exposure and uncertain risks.')]),
m('01-ionic-and-covalent-bonds','Ionic & covalent bonds',['Form ions','Build lattices','Share electrons'],[
p('Electron transfer','Metal atoms lose electrons → positive ions. Non-metals gain → negative ions. Protons stay unchanged.','Group 1/2: +1/+2 ions; Group 7/6: −1/−2 ions. Electron arrangements match a noble gas.'),
p('Charge → formula','Balance total charges: Mg²⁺ + 2Cl⁻ → MgCl₂; 2Na⁺ + O²⁻ → Na₂O.','Dot-and-cross ionic diagrams: brackets, ion charge and full outer shells; distinguish electron origins.'),
p('Ionic lattice','A giant, repeating 3D arrangement of opposite ions, with strong electrostatic attractions in all directions.','Many attractions need much energy to overcome → high melting/boiling. Not separate molecules.'),
p('Conductivity follows movement','Solid: ions held in fixed positions → cannot carry charge through it.','Molten/dissolved: ions free to move → conducts. Electrons do not carry current through the ionic liquid.'),
p('Covalent pairs','A single bond shares one pair; double shares two; triple shares three.','H₂, Cl₂, HCl: one single bond. O₂: double. N₂: triple. H₂O: two single; NH₃: three; CH₄: four.','Show lone pairs too: O has two in H₂O; N has one in NH₃; Cl has three.'),
p('Molecules & models','Strong bonds inside a molecule; weaker intermolecular forces between molecules. Boiling overcomes those forces.','Bigger molecules generally have stronger intermolecular forces. No mobile ions/electrons → no conduction.','2D formulae omit 3D shape; ball-and-stick bonds are not literal rods.')]),
m('02-structures-and-states','Structures & states',['Describe particles','Explain properties','Compare models'],[
p('Solid → liquid → gas','Solid: fixed arrangement, vibration. Liquid: close particles move past one another. Gas: widely spaced, rapid random motion.','Melting/freezing; boiling/condensing. Heating transfers energy; changes of state are physical.'),
p('Read melting & boiling data','Below melting point → solid. Between melting and boiling → liquid. Above boiling → gas.','State symbols: (s), (l), (g), (aq). Aqueous means dissolved in water.','Particles are not hard identical spheres: models omit forces, size differences and continuous movement.'),
p('Metals conduct & bend','Strong attraction between positive ions and delocalised electrons → giant metallic structure.','Electrons move and carry charge and transfer energy. Metal layers slide while metallic bonding remains.'),
p('Alloys resist bending','An alloy mixes a metal with other elements. Different-sized atoms distort regular layers.','Layers slide less easily → alloy is harder. Use a labelled particle drawing to explain, not just “stronger”.'),
p('Polymer chains','Many atoms joined by strong covalent bonds in long molecules. Forces act between chains.','Intermolecular forces are usually sufficient for polymers to be solid at room temperature.','A repeating unit in brackets with n represents many linked units.'),
p('Recognise giant structures','Diamond, graphite and silicon dioxide are giant covalent. Many strong bonds need much energy to break → high melting.','Contrast small molecules: melting/boiling does not break their internal covalent bonds.','Use diagrams, formulae and melting/conductivity data together to identify structure.')]),
m('03-carbon-and-nanoparticles','Carbon & nanoparticles',['Link carbon bonds','Apply structures','Assess tiny particles'],[
p('Diamond','Each carbon bonds to four others in a rigid giant covalent network. Many strong bonds → very hard, high melting.','No delocalised electrons or moving ions → does not conduct electricity. Useful for cutting.'),
p('Graphite & graphene','Graphite: each carbon bonds to three others in hexagonal layers. One electron per carbon is delocalised → conducts.','Weak forces between layers → slide → lubricant. Strong bonds within layers → high melting.','Graphene: a single layer; very strong and conducting, useful in composites/electronics.'),
p('Fullerenes & nanotubes','Fullerenes are hollow carbon cages/tubes, based on hexagonal rings; some also have five- or seven-sided rings. C₆₀ is a cage.','Large surface area: catalysts. Hollow cages: drug delivery. Cylindrical nanotubes: high tensile strength and conductivity → composites/electronics.'),
p('Size classes','Nanoparticles: **1–100 nm**. Fine particles: 100–2,500 nm. Coarse particles: 2,500–10,000 nm.','1 nm = 10⁻⁹ m. Smaller size increases surface area compared with volume; properties may differ from bulk material.'),
p('Calculate the ratio','Cube of side x: area = 6x²; volume = x³; **SA/V = 6/x**. Use the same length units.','Side 10 nm → SA/V 0.6 nm⁻¹; side 5 nm → 1.2 nm⁻¹. Halving size doubles the ratio.','More exposed surface per amount → less catalyst/coating may be needed.'),
p('Benefits & risks','Uses: catalysts, medicine, electronics, sunscreen and antibacterial coatings. Link each use to a useful property.','Small particles may enter the body; effects depend on material, dose and exposure route.','Compare benefit with toxicity/environmental evidence and uncertainties; do not assume all nanoparticles are safe or harmful.')])]

MAPS[2][0]["pics"]={0:("chem-pairs",80)}
MAPS[2][1]["pics"]={2:("chem-lattice",95)}
MAPS[2][2]["pics"]={2:("chem-layers",100)}
MAPS[2][3]["pics"]={1:("chem-layers",100)}
