from biology_course_maps import p,m
MAPS={1:[
m('00-atomic-structure-overview','Atomic structure overview',['Describe matter','Explain atoms','Predict properties'],[
p('Elements, compounds, mixtures','Element: one proton number. Compound: elements chemically joined in fixed proportions. Mixture: not chemically joined.','Balance equations with coefficients, never by changing formulae.'),
p('Separate physically','Insoluble solid → filtration. Dissolved solid → crystallisation. Solvent → simple distillation.','Miscible liquids → fractional distillation. Dyes → chromatography; pencil baseline above solvent.'),
p('Particles & isotopes','Proton +1, neutron 0, electron −1. Atomic number = protons; mass number = protons + neutrons.','Neutral atoms: protons = electrons. Ions gain/lose electrons. Isotopes differ in neutrons.','Aᵣ = sum(mass × % abundance)/100.'),
p('Electrons & models','First 20: shells fill 2,8,8,2. Same main group → same outer electrons; period → occupied shells.','Scattering evidence → tiny positive nucleus, mostly empty space. Bohr: shells; Chadwick: neutrons.'),
p('Group patterns','Group 0: full outer shell, unreactive; boiling point rises down group.','Group 1: loses 1 electron; reactivity rises down group. Group 7: gains 1; reactivity falls.','More reactive halogen displaces less reactive halide.'),
p('Table & transition metals','Mendeleev left gaps and predicted properties; modern order is proton number.','Transition metals: generally denser, stronger, harder, higher melting and less reactive than Group 1.','Many form coloured compounds, variable-charge ions and catalysts.')]),
m('01-atoms-isotopes-and-models','Atoms, isotopes & models',['Count particles','Arrange electrons','Follow the evidence'],[
p('Nucleus & charge','Protons +1 and neutrons 0 each have relative mass 1. Electrons −1 have tiny mass.','Atomic number = protons. Neutrons = mass number − atomic number.','Na-23: 11p, 12n, 11e. Na⁺: 11p, 12n, 10e.'),
p('Size & isotope averages','Atom radius ≈ 10⁻¹⁰ m; nucleus ≈ 10⁻¹⁴ m or less. Almost all mass is nuclear. **1 nm = 10⁻⁹ m.**','Isotopes: same protons, different neutrons. Aᵣ weights each isotope by abundance.','75% mass 35 + 25% mass 37 → **35.5**.'),
p('Shells & position','Lowest shells fill first: **2,8,8,2** for first 20 elements. O: 2,6; Na: 2,8,1; Ca: 2,8,8,2.','Period = occupied shells. Same main group = same outer electrons → similar reactions.','Metals generally lose electrons; non-metals gain/share.'),
p('Atoms → ions','Losing negative electrons produces a **positive ion**; gaining them produces a negative ion.','The number of protons stays unchanged: it remains the same element.','Full outer shells help explain the stability of noble gases.'),
p('Scattering conclusions','Most alpha particles pass → atom mostly empty space.','Some deflect → nucleus is positive and repels positive alpha particles.','Very few return → tiny, dense nucleus holds most mass; contradicts spread-out positive charge.'),
p('Changing models','Indivisible spheres → discovery of electron → plum pudding. Scattering → nuclear model.','Bohr: specific electron shells. Later work: protons. Chadwick: neutrons.','New experimental evidence can replace a scientific model.')],{3:('chem-ion',95)}),
m('02-substances-and-separation','Substances & separation',['Identify & represent','Separate solids','Separate liquids'],[
p('What is the substance?','Element: atoms of one element. Compound: different elements chemically combined in a fixed ratio.','Mixture: substances retain chemical properties and can be separated physically. Compounds need chemical reactions.'),
p('Symbols & equations','H₂O = 2H and 1O; Ca(OH)₂ = 1Ca, 2O, 2H. Use correct upper/lower case in symbols.','**2Mg + O₂ → 2MgO.** Count each element on both sides; change coefficients only.','Binary names often end -ide; -ate names usually include oxygen.'),
p('Filtration','Separates **insoluble solid** from liquid. Residue stays on filter; filtrate passes through.','Dissolved salt passes through too. Salt + sand: dissolve salt, filter sand, crystallise filtrate.'),
p('Crystallisation','Partly evaporate solvent → concentrated solution → cool → crystals form.','Filter crystals and dry them. Avoid heating hydrated salts strongly to complete dryness.','Wear goggles; handle hot glassware carefully.'),
p('Distillation','Simple: boil liquid, cool vapour in condenser, collect liquid distillate. Recover water from salt solution.','Fractional: column gives repeated evaporation/condensation to separate miscible liquids by boiling point.','Lower-boiling fraction usually comes first; cooling water enters condenser at bottom.'),
p('Chromatography','Components have different attractions to solvent and stationary phase, so travel different distances.','Pencil baseline **above solvent**; small spots; mark solvent front. Ink could dissolve; submerged spots wash off.','No new substances form in these physical separations.')]),
m('03-periodic-patterns','Periodic patterns',['Arrange & explain','Compare the groups','Apply predictions'],[
p('Modern & historical tables','Modern order: **atomic number**. Groups link outer electrons and reactions; periods link occupied shells.','Mendeleev used mass/properties, left gaps and predicted missing elements. Discoveries supported predictions; isotopes explain mass-order anomalies.'),
p('Group 0','Full outer shell: 8 electrons except **helium has 2**. Very unreactive, monatomic gases.','Boiling point increases with atomic mass down the group. Use the trend to predict values.'),
p('Group 1','One outer electron → **+1 ions**. Li, Na, K: water → hydroxide + H₂; oxygen → oxides; chlorine → chlorides.','**2Na + 2H₂O → 2NaOH + H₂.** Alkaline solution; reactions get more vigorous Li → Na → K.','Down group: more distance/shielding → outer electron lost more easily → reactivity rises.'),
p('Group 7','Seven outer electrons; gain one → **−1 ions**. Diatomic Cl₂, Br₂, I₂. Metal halides ionic; non-metal compounds covalent.','Cl₂ green gas; Br₂ red-brown liquid; I₂ grey-black solid. Melting/boiling points rise down group.','More distance/shielding → weaker attraction for incoming electron → reactivity falls.'),
p('Halogen displacement','More reactive halogen displaces less reactive halogen from its aqueous salt.','**Cl₂ + 2KBr → 2KCl + Br₂.** Ionic: Cl₂ + 2Br⁻ → 2Cl⁻ + Br₂.','Iodine cannot displace chlorine from chloride. Use group position to predict.'),
p('Transition metals','Cr, Mn, Fe, Co, Ni, Cu: generally stronger/harder/denser, higher melting and less reactive than Group 1.','Many have variable ion charges, coloured compounds and catalytic uses.','Fe²⁺/Fe³⁺; blue copper sulfate; iron/nickel catalysts. Trends have exceptions.')]) ]}

MAPS[2]=[
m('00-bonding-overview','Bonding & properties',['Bond particles','Explain behaviour','Choose materials'],[
p('Three strong bonds','Ionic: attraction between opposite ions after electron transfer. Covalent: shared electron pairs attract both nuclei.','Metallic: positive ions attract delocalised electrons. Identify the charged particles in explanations.'),
p('Structure decides properties','Ionic lattices: high melting; conduct only molten or dissolved, when ions move.','Small molecules: low melting/boiling; weak forces between molecules. No mobile charged particles.','Giant covalent: many strong bonds → high melting.'),
p('States & models','Solid: particles vibrate in fixed positions. Liquid: close particles move past each other. Gas: particles far apart, moving randomly.','At a change of state, energy changes attractions/spacing, not particle identity. Model drawings simplify size, forces and movement.'),
p('Metals & polymers','Metals conduct through mobile delocalised electrons; layers can slide. Different-sized alloy atoms hinder sliding.','Polymers: long molecules, strong bonds along each chain, forces between chains; most are solid at room temperature.'),
p('Carbon structures','Diamond: four bonds per carbon, rigid and hard, no free electrons. Graphite: three bonds; weak forces between layers let them slide.','Graphene: one strong, conducting layer. Fullerenes: hollow cages; nanotubes: strong conducting cylinders.'),
p('Nanoparticles','1–100 nm: large surface area : volume ratio. Small amounts can be effective catalysts or coatings.','Uses include medicine, electronics, sunscreen and antibacterial surfaces. Properties differ from bulk material; assess exposure and uncertain risks.')]),
m('01-ionic-and-covalent-bonds','Ionic & covalent bonds',['Form ions','Build lattices','Share electrons'],[
p('Electron transfer','Metal atoms lose electrons → positive ions. Non-metals gain → negative ions. Protons stay unchanged.','Group 1/2: +1/+2 ions; Group 7/6: −1/−2 ions. Electron arrangements match a noble gas.'),
p('Charge → formula','Balance total charges: Mg²⁺ + 2Cl⁻ → MgCl₂; 2Na⁺ + O²⁻ → Na₂O.','Dot-and-cross ionic diagrams: brackets, ion charge and full outer shells; distinguish electron origins.'),
p('Ionic lattice','A giant, repeating 3D arrangement of opposite ions, with strong electrostatic attractions in all directions.','Many attractions need much energy to overcome → high melting/boiling. Not separate molecules.'),
p('Conductivity follows movement','Solid: ions held in fixed positions → cannot carry charge through it.','Molten/dissolved: ions free to move → conducts. Electrons do not carry current through the ionic liquid.'),
p('Covalent pairs','A single bond shares one pair; double shares two; triple shares three.','H₂, Cl₂, HCl: one single bond. O₂: double. N₂: triple. H₂O: two single; NH₃: three; CH₄: four.','Show lone pairs too: O has two in H₂O; N has one in NH₃; Cl has three.'),
p('Molecules & models','Strong bonds inside a molecule; weaker intermolecular forces between molecules. Boiling overcomes those forces.','Bigger molecules generally have stronger intermolecular forces. No mobile ions/electrons → no conduction.','2D formulae omit 3D shape; ball-and-stick bonds are not literal rods.')]),
m('02-structures-and-states','Structures & states',['Describe particles','Explain properties','Compare models'],[
p('Solid → liquid → gas','Solid: fixed arrangement, vibration. Liquid: close particles move past one another. Gas: widely spaced, rapid random motion.','Melting/freezing; boiling/condensing. Heating transfers energy; changes of state are physical.'),
p('Read melting & boiling data','Below melting point → solid. Between melting and boiling → liquid. Above boiling → gas.','State symbols: (s), (l), (g), (aq). Aqueous means dissolved in water.','Particles are not hard identical spheres: models omit forces, size differences and continuous movement.'),
p('Metals conduct & bend','Strong attraction between positive ions and delocalised electrons → giant metallic structure.','Electrons move and carry charge and transfer energy. Metal layers slide while metallic bonding remains.'),
p('Alloys resist bending','An alloy mixes a metal with other elements. Different-sized atoms distort regular layers.','Layers slide less easily → alloy is harder. Use a labelled particle drawing to explain, not just “stronger”.'),
p('Polymer chains','Many atoms joined by strong covalent bonds in long molecules. Forces act between chains.','Intermolecular forces are usually sufficient for polymers to be solid at room temperature.','A repeating unit in brackets with n represents many linked units.'),
p('Recognise giant structures','Diamond, graphite and silicon dioxide are giant covalent. Many strong bonds need much energy to break → high melting.','Contrast small molecules: melting/boiling does not break their internal covalent bonds.','Use diagrams, formulae and melting/conductivity data together to identify structure.')]),
m('03-carbon-and-nanoparticles','Carbon & nanoparticles',['Link carbon bonds','Apply structures','Assess tiny particles'],[
p('Diamond','Each carbon bonds to four others in a rigid giant covalent network. Many strong bonds → very hard, high melting.','No delocalised electrons or moving ions → does not conduct electricity. Useful for cutting.'),
p('Graphite & graphene','Graphite: each carbon bonds to three others in hexagonal layers. One electron per carbon is delocalised → conducts.','Weak forces between layers → slide → lubricant. Strong bonds within layers → high melting.','Graphene: a single layer; very strong and conducting, useful in composites/electronics.'),
p('Fullerenes & nanotubes','Fullerenes are hollow carbon cages/tubes, based on hexagonal rings; some also have five- or seven-sided rings. C₆₀ is a cage.','Large surface area: catalysts. Hollow cages: drug delivery. Cylindrical nanotubes: high tensile strength and conductivity → composites/electronics.'),
p('Size classes','Nanoparticles: **1–100 nm**. Fine particles: 100–2,500 nm. Coarse particles: 2,500–10,000 nm.','1 nm = 10⁻⁹ m. Smaller size increases surface area compared with volume; properties may differ from bulk material.'),
p('Calculate the ratio','Cube of side x: area = 6x²; volume = x³; **SA/V = 6/x**. Use the same length units.','Side 10 nm → SA/V 0.6 nm⁻¹; side 5 nm → 1.2 nm⁻¹. Halving size doubles the ratio.','More exposed surface per amount → less catalyst/coating may be needed.'),
p('Benefits & risks','Uses: catalysts, medicine, electronics, sunscreen and antibacterial coatings. Link each use to a useful property.','Small particles may enter the body; effects depend on material, dose and exposure route.','Compare benefit with toxicity/environmental evidence and uncertainties; do not assume all nanoparticles are safe or harmful.')])]

MAPS[2][0]["pics"]={0:("chem-pairs",80)}
MAPS[2][1]["pics"]={2:("chem-lattice",95)}
MAPS[2][2]["pics"]={2:("chem-layers",100)}
MAPS[2][3]["pics"]={1:("chem-layers",100)}

MAPS[3]=[
m('00-quantitative-overview','Quantitative chemistry',['Count & conserve','Use the equation','Judge the outcome'],[
p('Mass & formulae','Atoms are rearranged, not created/destroyed. Closed system: reactant mass = product mass.','Gas entering/leaving explains apparent mass change. Mᵣ = sum of Aᵣ values in formula; no unit.','Balance coefficients, never change formula subscripts.'),
p('Moles are a counting unit','One mole contains **6.02 × 10²³** stated particles. Molar mass in g/mol is numerically equal to Mᵣ.','**n = mass / molar mass.** Particles = n × Avogadro constant.'),
p('Ratios & limiting reactants','Mass → moles → equation ratio → required moles → mass.','Limiting reactant runs out and limits product; excess remains. Compare moles divided by each coefficient.','From masses: convert to moles, divide by smallest, obtain whole-number ratio.'),
p('Solutions & gases','**1 dm³ = 1,000 cm³.** Mass concentration = g / dm³; molar concentration = mol / dm³.','Titration: known cV → ratio → unknown n/V.','At RTP, gas volume = **n × 24 dm³**; gas ratios follow equation coefficients.'),
p('Yield & atom economy','Yield = actual / theoretical × 100%. Losses, side reactions and incomplete reactions lower yield.','Atom economy = desired-product mass / total reactant mass from equation × 100%; include coefficients.','Compare rate, yield, waste, equilibrium and useful by-products.'),
p('Reliable measurements','Repeat, calculate mean and show spread. Half-range can estimate uncertainty when requested.','Percentage uncertainty = absolute uncertainty / reading × 100. Repeats reduce random effects, not systematic errors.','Keep units consistent and round only the final answer.')]),
m('01-moles-and-reacting-masses','Moles & reacting masses',['Count accurately','Follow the recipe','Check what runs out'],[
p('Mᵣ & composition','Ca(OH)₂: 40 + 2 × (16 + 1) = **74**. Brackets multiply every atom inside.','Oxygen percentage = 32/74 × 100 = **43.2%**. Mᵣ has no unit; molar mass is 74 g/mol.'),
p('Moles & particles','n = mass / molar mass. 11 g CO₂ / 44 g/mol = **0.25 mol**.','Particles = n × 6.02 × 10²³. This is 1.505 × 10²³ CO₂ molecules; each has three atoms.','State whether counting atoms, molecules, ions or electrons.'),
p('Reacting masses','**2Mg + O₂ → 2MgO.** 6.0 g Mg / 24 = 0.25 mol Mg.','Mg : MgO = 2 : 2 → 0.25 mol MgO. Mass = 0.25 × 40 = **10 g MgO**, oxygen in excess.','Coefficients are mole ratios, not mass ratios.'),
p('Find equation coefficients','Divide each mass by its molar mass; divide all moles by smallest; multiply to whole numbers.','2.4 g Mg, 1.6 g O₂, 4.0 g MgO → 0.10 : 0.05 : 0.10 mol → **2 : 1 : 2**.','Check atoms and total mass on both sides.'),
p('Limiting vs excess','0.30 mol Mg + 0.10 mol O₂: oxygen needs only 0.20 mol Mg.','O₂ is limiting. MgO formed = **0.20 mol**; Mg left = **0.10 mol**.','Use limiting amount for theoretical yield; extra excess reactant cannot increase it.'),
p('Mass & uncertainty','An open vessel gains mass if oxygen enters; loses mass if gas escapes. Count all substances to conserve mass.','Readings 24.2, 24.4, 24.6 → mean 24.4; range 0.4; half-range uncertainty **±0.2**.','Percentage uncertainty = 0.2/24.4 × 100 = 0.82%.')]),
m('02-solutions-and-gases','Solutions & gases',['Choose units','Use reaction ratios','Convert gas amounts'],[
p('Mass concentration','c in g/dm³ = mass in g / solution volume in dm³. Mass = cV.','250 cm³ = **0.250 dm³**. 5.0 g in 0.250 dm³ → **20 g/dm³**.','Same solute, double final volume → half concentration.'),
p('Molar concentration','**n = cV** with c in mol/dm³ and V in dm³. Rearrange: c = n/V.','0.200 mol/dm³ × 0.150 dm³ = 0.0300 mol. For NaOH, mass = 0.0300 × 40 = **1.20 g**.','mol/dm³ × molar mass → g/dm³.'),
p('Titration route','Take mean of concordant titres, excluding rough trial. Convert both volumes to dm³.','Known moles = known c × V. Use balanced equation ratio. Unknown concentration = unknown moles / its volume.'),
p('A 1 : 2 example','**H₂SO₄ + 2NaOH → Na₂SO₄ + 2H₂O.**','20.0 cm³ acid at 0.100 mol/dm³ → 0.00200 mol acid → 0.00400 mol NaOH.','If NaOH volume is 25.0 cm³, c = 0.00400/0.0250 = **0.160 mol/dm³**.'),
p('Gas volume at RTP','One mole occupies **24 dm³** at 20 °C and 1 atmosphere. Equal moles → equal gas volumes at same conditions.','V = 24n; n = V/24, with V in dm³. 1 dm³ = 1,000 cm³.','4.4 g CO₂ / 44 = 0.10 mol → **2.4 dm³**.'),
p('Gas equation ratios','**2H₂ + O₂ → 2H₂O**: 60 cm³ H₂ needs 30 cm³ O₂ at the same conditions.','For mass to gas: mass → moles → equation ratio → gas moles → volume.','Do not apply the gas-volume rule to a solid or liquid; identify limiting gas if both amounts are given.')]),
m('03-yield-and-atom-economy','Yield & atom economy',['Predict & measure','Account for atoms','Choose a pathway'],[
p('Theoretical maximum','Use mass → moles → equation ratio → product mass. Check limiting reactant first.','Example: CaCO₃ → CaO + CO₂. 25.0 g CaCO₃ / 100 = 0.250 mol → 0.250 × 56 = **14.0 g CaO**.'),
p('Percentage yield','**Yield = actual / theoretical × 100%.** If actual CaO is 11.2 g: 11.2/14.0 × 100 = **80.0%**.','Actual = theoretical × yield/100. Theoretical = actual / (yield/100).'),
p('Why yield is lower','Reversible reaction may not finish; side reactions consume reactants; product is lost in transfer/separation.','Atoms are still conserved. Apparent yield above 100% suggests wet/impure product or measurement error.'),
p('Atom economy','Desired-product coefficient × Mᵣ divided by sum of all reactant coefficient × Mᵣ; then × 100%.','CaCO₃ → CaO + CO₂: for desired CaO, 56/100 × 100 = **56%**.','Other 44% becomes CO₂, even if every atom reacts correctly.'),
p('Keep the ideas separate','Yield: proportion of the expected product actually collected. Atom economy: proportion of starting mass directed into desired product.','A process can have high yield but low atom economy. Addition reactions with one product have 100% atom economy.'),
p('Evidence → decision','Higher atom economy reduces waste and resource/disposal costs. But compare yield, rate, energy, equilibrium and useful by-products too.','Support a choice using the supplied data and acknowledge a trade-off. Repeats/uncertainty help judge measured yield.')])]

for item in MAPS[3]: item["pics"]={2:("chem-route",85)}
MAPS[3][3]["pics"]={0:("chem-route",85)}

MAPS[3][2]["pics"]={2:("chem-titration",85)}

MAPS[4]=[
m('00-chemical-changes-overview','Chemical changes',['Predict reactions','Make & measure salts','Drive electrolysis'],[
p('Reactivity & displacement','More reactive metals form positive ions more readily and displace less reactive metals.','Mg > Zn > Fe > H > Cu: Mg/Zn/Fe react with dilute HCl or H₂SO₄; Cu does not.','Zn + Cu²⁺ → Zn²⁺ + Cu.'),
p('Redox & extraction','Oxidation: gain oxygen or lose electrons. Reduction: lose oxygen or gain electrons.','Below carbon: oxide can be reduced using carbon. More reactive metals need electrolysis. Gold may occur as the element.'),
p('Acids & salts','H⁺ + OH⁻ → H₂O. Metal + acid → salt + H₂; oxide/hydroxide + acid → salt + water.','Carbonate + acid also gives CO₂. HCl → chlorides; H₂SO₄ → sulfates; HNO₃ → nitrates.','Strong = fully ionised; concentrated = much solute per volume.'),
p('Three practical routes','Insoluble base + acid: add excess, filter, concentrate, cool, filter/dry crystals.','Titration: pipette alkali, burette acid, indicator; swirl, dropwise endpoint, concordant titres.','Electrolysis: inert electrodes, DC; predict and test separate electrode products.'),
p('Electrode rules','Molten/dissolved ions can move. Positive ions → negative cathode → reduction. Negative ions → positive anode → oxidation.','Molten binary compound: metal at cathode, non-metal at anode.','Aqueous: H₂ instead of metals above H; halogen at anode if halide, otherwise O₂.'),
p('Aluminium & half-equations','Cryolite lowers melting/operating temperature. Al³⁺ + 3e⁻ → Al.','2O²⁻ → O₂ + 4e⁻. Oxygen reacts with carbon anodes, so replace them.','Balance atoms AND charge. Electrons travel in wires; ions carry current through electrolyte.')]),
m('01-reactivity-and-redox','Reactivity & redox',['Order the metals','Follow electrons','Extract the element'],[
p('Reactivity order','K > Na > Li > Ca > Mg > Al > C > Zn > Fe > H > Cu > Ag > Au. C and H are comparison points.','More reactive → greater tendency to lose electrons and form positive ions. Aluminium has a protective oxide layer.'),
p('Water & acid evidence','Cold water: K/Na/Li react readily; Ca reacts; Mg very slow; Zn/Fe/Cu no significant reaction.','Water products: hydroxide + H₂. Dilute HCl/H₂SO₄: Mg rapid, Zn slower, Fe slower still; Cu no reaction.','Compare under controlled concentration, temperature and surface area.'),
p('Displacement','A more reactive metal displaces a less reactive one. Zn + CuSO₄ → ZnSO₄ + Cu.','Ionic: **Zn + Cu²⁺ → Zn²⁺ + Cu**. Sulfate spectator ions cancel.','Copper deposit; blue solution fades. Use several results to deduce an unknown order.'),
p('OIL RIG','Oxidation Is Loss; Reduction Is Gain of electrons. **Zn → Zn²⁺ + 2e⁻**: oxidation.','**Cu²⁺ + 2e⁻ → Cu**: reduction. Atoms and total charges balance.','Metal + acid: metal oxidised; 2H⁺ + 2e⁻ → H₂ is reduction.'),
p('Oxygen definitions','Oxidation gains oxygen; reduction loses oxygen.','**2CuO + C → 2Cu + CO₂**: CuO reduced; carbon oxidised. Redox changes happen together.','Copper oxide loses oxygen; do not say the copper ions lose electrons.'),
p('Choose extraction','Unreactive gold may be found as metal. Most metals occur in compounds.','Metal below carbon: carbon can reduce its oxide. More reactive metal, or one that reacts with carbon: electrolysis may be used.','Melting and electrical current require energy; evaluate cost using supplied data.')]),
m('02-acids-and-salts','Acids & salts',['Understand solutions','Predict products','Prepare pure crystals'],[
p('pH & neutralisation','Acid: H⁺ in water; alkali: OH⁻. Below pH 7 acidic; 7 neutral; above 7 alkaline.','**H⁺ + OH⁻ → H₂O.** Universal indicator estimates pH; a calibrated probe gives a numerical reading.','Equal volumes need not contain equal reacting amounts.'),
p('Strength vs concentration','Strong acids fully ionise: HCl, HNO₃, H₂SO₄. Weak acids partly ionise: ethanoic, citric, carbonic.','Concentrated/dilute describes amount per volume, not ionisation.','pH falls by 1 → H⁺ concentration ×10. pH 2 has 100× the H⁺ of pH 4.'),
p('Acid reaction patterns','Metal + acid → salt + H₂. Metal oxide/hydroxide + acid → salt + water.','Carbonate + acid → salt + water + CO₂. H₂ gives squeaky pop; CO₂ turns limewater cloudy.'),
p('Name & formulate salts','HCl → chloride; H₂SO₄ → sulfate; HNO₃ → nitrate. Metal supplies positive ion/name.','Balance charges: Mg²⁺ + 2NO₃⁻ → Mg(NO₃)₂. 2Na⁺ + SO₄²⁻ → Na₂SO₄.','CuO + H₂SO₄ → CuSO₄ + H₂O.'),
p('Salt practical: react & filter','Warm dilute acid gently; remove burner. Add insoluble oxide/carbonate in small portions, stirring, until excess remains.','Excess solid ensures all acid reacts. Filter off solid; salt solution is **filtrate**.','Goggles; avoid boiling/splashing acid.'),
p('Concentrate & crystallise','Gently evaporate some water using water bath/electric heater. Cool to form crystals.','Filter, rinse with a little cold distilled water and dry between filter papers. Do not strongly heat to dryness.','Soluble alkali cannot be filtered off: find exact volumes by titration instead.')]),
m('03-titration','Titration',['Measure accurately','Find the endpoint','Calculate & apply'],[
p('Pipette & flask','Rinse volumetric pipette with alkali; use filler to transfer a fixed volume into conical flask.','Add a few drops of indicator; use a white tile. Goggles; never mouth-pipette.','Flask may contain distilled water: it changes volume but not moles of alkali.'),
p('Burette preparation','Rinse burette with acid, fill, remove jet air bubble and filling funnel.','Read bottom of meniscus at eye level. Record initial value; starting at zero is unnecessary.','Water left in burette dilutes acid, changing concentration.'),
p('Endpoint technique','Add acid while swirling; near endpoint add drop by drop to first permanent colour change.','Acid into alkali: phenolphthalein pink → colourless; methyl orange yellow → orange at endpoint.','Universal indicator lacks a sharp single change.'),
p('Repeat & average','Titre = final − initial reading. Rough trial locates endpoint; exclude it from mean.','Repeat accurately to concordant titres; use tolerance specified. Mean only the concordant accurate titres.','Rinse flask splashes down with distilled water without changing reacting moles.'),
p('Moles from a titre','Known moles = **cV**; convert cm³ to dm³. Use balanced equation ratio, then unknown c = n/V.','20.0 cm³ 0.100 mol/dm³ HCl → 0.00200 mol HCl.','With 25.0 cm³ NaOH and 1:1 ratio: c = 0.00200/0.0250 = **0.0800 mol/dm³**.'),
p('Mass concentration & crystals','For NaOH, multiply by 40 g/mol: 0.0800 mol/dm³ → **3.20 g/dm³**.','To make pure salt: repeat exact reacting volumes without indicator; concentrate and crystallise.','Check acid formula: H₂SO₄ needs two NaOH per acid molecule; do not assume 1:1.')]),
m('04-electrolysis','Electrolysis',['Move charged particles','Predict the products','Apply & investigate'],[
p('Electrolyte & electrodes','Ions move only when molten/dissolved. Positive ions go to negative cathode; negative ions to positive anode.','Cathode: gain electrons, reduction. Anode: lose electrons, oxidation. Electrons move in wires, ions in liquid.'),
p('Molten binary compounds','Metal at cathode; non-metal at anode. No competing water ions.','Molten PbBr₂: **Pb²⁺ + 2e⁻ → Pb**; **2Br⁻ → Br₂ + 2e⁻**.','Balance atoms and total charge; halogens are diatomic.'),
p('Aqueous product rules','Water adds H⁺ and OH⁻. At cathode: H₂ if metal is above hydrogen, otherwise metal.','At anode with inert electrodes: halogen if halide present, otherwise O₂.','NaCl(aq): H₂/Cl₂; CuCl₂(aq): Cu/Cl₂; CuSO₄(aq): Cu/O₂.'),
p('Useful half-equations','**2H⁺ + 2e⁻ → H₂.** **Cu²⁺ + 2e⁻ → Cu.**','**2Cl⁻ → Cl₂ + 2e⁻.** **4OH⁻ → O₂ + 2H₂O + 4e⁻.**','Oxidation puts electrons on product side; reduction uses them on reactant side.'),
p('Aluminium extraction','Molten Al₂O₃/cryolite mixture needs lower temperature than pure Al₂O₃. **Al³⁺ + 3e⁻ → Al**.','**2O²⁻ → O₂ + 4e⁻**. Oxygen reacts with carbon anodes → CO₂; replace anodes.','Energy needed for heat and current; carbon cannot reduce aluminium oxide.'),
p('Aqueous practical','Hypothesis: changing dissolved compound changes products. Use inert electrodes/DC; compare solutions at same voltage, time, concentration and electrode setup.','Test H₂: pop; O₂: relights glowing splint; Cl₂: bleaches damp litmus. Record metal deposits too.','Repeat; goggles, ventilation for chlorine; switch off before adjusting electrodes.')])]

MAPS[4][0]["pics"]={4:("chem-electrodes",85)}
MAPS[4][3]["pics"]={4:("chem-titration",85)}
MAPS[4][4]["pics"]={0:("chem-electrodes",85)}
