from biology_course_maps import p,m
MAPS={1:[
m('00-atomic-structure-overview','Atomic structure overview',['Describe matter','Explain atoms','Predict properties'],[
p('Elements, compounds, mixtures','Element: one proton number. Compound: elements chemically joined in fixed proportions. Mixture: not chemically joined.','Balance equations with coefficients, never by changing formulae.'),
p('Separate physically','Insoluble solid → filtration. Dissolved solid → crystallisation. Solvent → simple distillation.','Miscible liquids → fractional distillation. Dyes → chromatography; pencil baseline above solvent.'),
p('Particles & isotopes','Proton +1, neutron 0, electron −1. Atomic number = protons; mass number = protons + neutrons.','Neutral atoms: protons = electrons. Ions gain/lose electrons. Isotopes differ in neutrons.','Aᵣ = sum(mass × % abundance)/100.'),
p('Electrons & models','First 20: shells fill 2,8,8,2. Same main group → same outer electrons; period → occupied shells.','Scattering evidence → tiny positive nucleus, mostly empty space. Bohr: shells; Chadwick: neutrons.'),
p('Group patterns','Group 0: full outer shell, unreactive; boiling point rises down group.','Group 1: loses 1 electron; reactivity rises down group. Group 7: gains 1; reactivity falls.','More reactive halogen displaces less reactive halide.'),
p('Table & transition metals','Mendeleev left gaps and predicted properties; modern order is proton number.','Transition metals: generally denser, stronger, harder, higher melting and less reactive than Group 1.','Many form coloured compounds, variable-charge ions and catalysts.')]),
m('01-atoms-isotopes-and-models','Atoms, isotopes & models',['Count particles','Arrange electrons','Follow the evidence'],[
p('Nucleus & charge','Protons +1 and neutrons 0 each have relative mass 1. Electrons −1 have tiny mass.','Atomic number = protons. Neutrons = mass number − atomic number.','Na-23: 11p, 12n, 11e. Na⁺: 11p, 12n, 10e.'),
p('Size & isotope averages','Atom radius ≈ 10⁻¹⁰ m; nucleus ≈ 10⁻¹⁴ m or less. Almost all mass is nuclear. **1 nm = 10⁻⁹ m.**','Isotopes: same protons, different neutrons. Aᵣ weights each isotope by abundance.','75% mass 35 + 25% mass 37 → **35.5**.'),
p('Shells & position','Lowest shells fill first: **2,8,8,2** for first 20 elements. O: 2,6; Na: 2,8,1; Ca: 2,8,8,2.','Period = occupied shells. Same main group = same outer electrons → similar reactions.','Metals generally lose electrons; non-metals gain/share.'),
p('Atoms → ions','Losing negative electrons produces a **positive ion**; gaining them produces a negative ion.','The number of protons stays unchanged: it remains the same element.','Full outer shells help explain the stability of noble gases.'),
p('Scattering conclusions','Most alpha particles pass → atom mostly empty space.','Some deflect → nucleus is positive and repels positive alpha particles.','Very few return → tiny, dense nucleus holds most mass; contradicts spread-out positive charge.'),
p('Changing models','Indivisible spheres → discovery of electron → plum pudding. Scattering → nuclear model.','Bohr: specific electron shells. Later work: protons. Chadwick: neutrons.','New experimental evidence can replace a scientific model.')],{3:('chem-ion',95)}),
m('02-substances-and-separation','Substances & separation',['Identify & represent','Separate solids','Separate liquids'],[
p('What is the substance?','Element: atoms of one element. Compound: different elements chemically combined in a fixed ratio.','Mixture: substances retain chemical properties and can be separated physically. Compounds need chemical reactions.'),
p('Symbols & equations','H₂O = 2H and 1O; Ca(OH)₂ = 1Ca, 2O, 2H. Use correct upper/lower case in symbols.','**2Mg + O₂ → 2MgO.** Count each element on both sides; change coefficients only.','Binary names often end -ide; -ate names usually include oxygen.'),
p('Filtration','Separates **insoluble solid** from liquid. Residue stays on filter; filtrate passes through.','Dissolved salt passes through too. Salt + sand: dissolve salt, filter sand, crystallise filtrate.'),
p('Crystallisation','Partly evaporate solvent → concentrated solution → cool → crystals form.','Filter crystals and dry them. Avoid heating hydrated salts strongly to complete dryness.','Wear goggles; handle hot glassware carefully.'),
p('Distillation','Simple: boil liquid, cool vapour in condenser, collect liquid distillate. Recover water from salt solution.','Fractional: column gives repeated evaporation/condensation to separate miscible liquids by boiling point.','Lower-boiling fraction usually comes first; cooling water enters condenser at bottom.'),
p('Chromatography','Components have different attractions to solvent and stationary phase, so travel different distances.','Pencil baseline **above solvent**; small spots; mark solvent front. Ink could dissolve; submerged spots wash off.','No new substances form in these physical separations.')]),
m('03-periodic-patterns','Periodic patterns',['Arrange & explain','Compare the groups','Apply predictions'],[
p('Modern & historical tables','Modern order: **atomic number**. Groups link outer electrons and reactions; periods link occupied shells.','Mendeleev used mass/properties, left gaps and predicted missing elements. Discoveries supported predictions; isotopes explain mass-order anomalies.'),
p('Group 0','Full outer shell: 8 electrons except **helium has 2**. Very unreactive, monatomic gases.','Boiling point increases with atomic mass down the group. Use the trend to predict values.'),
p('Group 1','One outer electron → **+1 ions**. Li, Na, K: water → hydroxide + H₂; oxygen → oxides; chlorine → chlorides.','**2Na + 2H₂O → 2NaOH + H₂.** Alkaline solution; reactions get more vigorous Li → Na → K.','Down group: more distance/shielding → outer electron lost more easily → reactivity rises.'),
p('Group 7','Seven outer electrons; gain one → **−1 ions**. Diatomic Cl₂, Br₂, I₂. Metal halides ionic; non-metal compounds covalent.','Cl₂ green gas; Br₂ red-brown liquid; I₂ grey-black solid. Melting/boiling points rise down group.','More distance/shielding → weaker attraction for incoming electron → reactivity falls.'),
p('Halogen displacement','More reactive halogen displaces less reactive halogen from its aqueous salt.','**Cl₂ + 2KBr → 2KCl + Br₂.** Ionic: Cl₂ + 2Br⁻ → 2Cl⁻ + Br₂.','Iodine cannot displace chlorine from chloride. Use group position to predict.'),
p('Transition metals','Cr, Mn, Fe, Co, Ni, Cu: generally stronger/harder/denser, higher melting and less reactive than Group 1.','Many have variable ion charges, coloured compounds and catalytic uses.','Fe²⁺/Fe³⁺; blue copper sulfate; iron/nickel catalysts. Trends have exceptions.')]) ]}
