from biology_course_maps import p,m
MAPS={1:[
m('00-macbeth-overview','Macbeth',['Trace the downfall','Follow relationships','Explain the drama'],[
p('Five-act journey','1: prophecy and choice. 2: Duncan murdered; Macbeth crowned. 3: Banquo killed, Fleance escapes; ghost at banquet.','4: misleading assurances; Macduff’s family killed. 5: Lady Macbeth dies; resistance defeats Macbeth; Malcolm restores rule.'),
p('Ambition → insecurity','A praised defender becomes a king who attacks his own people. He gains power but loses peace.','The witches tempt; Macbeth chooses. “Vaulting ambition” (1.7) shows he understands the danger.','New crimes try to protect the first crime; violence escalates.'),
p('The marriage changes','Lady Macbeth initially directs the plot and challenges his manhood. After Duncan’s murder she manages his panic.','Macbeth later excludes her from plans. Her sleepwalking reveals guilt; his power leaves him isolated.','Shared ambition → divided knowledge → loneliness.'),
p('Contrasts & victims','Banquo hears prophecy but warns of “instruments of darkness” (1.3). Macduff combines courage with grief.','Duncan’s trust exposes betrayal; Lady Macduff and her son reveal tyranny’s human cost.','Malcolm offers a different model of leadership.'),
p('Motifs & stagecraft','Blood: bravery → murder → guilt. Sleep: rest → lost innocence. Washing cannot erase responsibility.','Asides/soliloquies expose hidden thoughts. Dramatic irony makes trust dangerous. Public banquet exposes private fear.'),
p('Answer the question','Extract: follow language, behaviour and shifts across the passage; explain audience effects.','Essay: argue across beginning, middle and end. Use precise evidence and analyse Shakespeare’s choices.','15-mark extract; 25-mark essay includes 5 for writing accuracy.')]),
m('01-characters-and-relationships','Characters & relationships',['Compare the couple','Study alternatives','Track the victims'],[
p('Macbeth’s transformation','“Brave Macbeth” (1.2) → secret desire → hesitation → murder → independent tyranny.','“Fruitless crown” (3.1): power without secure inheritance. “Walking shadow” (5.5): achievement feels empty.','Pity for wasted potential can coexist with condemnation.'),
p('Lady Macbeth’s change','“Unsex me here” (1.5): she tries to suppress compassion. Challenges manhood; controls the plan.','“A little water” (2.2) minimises guilt; sleepwalking and “damned spot” (5.1) expose its persistence.','Her requests for cruelty can reveal vulnerability, not effortless evil.'),
p('Marriage: power shifts','Act 1: “partner of greatness”; shared ambition. Act 2: she returns daggers and covers panic.','Act 3: he plans Banquo’s death without her; she tries to protect his image at the banquet.','Act 5: emotional isolation. He is not controlled by her throughout.'),
p('Banquo & Macduff','Banquo is a foil: shares curiosity about prophecy but warns of deception; Fleance’s escape keeps Macbeth insecure.','Macduff resists tyranny and grieves: “I must also feel it as a man” (4.3).','His duty to Scotland conflicts painfully with family safety.'),
p('Duncan & Malcolm','Duncan rewards service but misjudges loyalty. His trust makes Macbeth’s betrayal more disturbing.','Malcolm tests Macduff before trusting him; responsible kingship contrasts with self-protection.','Ending restores political order, without undoing suffering.'),
p('Witches & innocents','Witches offer tempting predictions and double meanings; they never tell Macbeth to kill Duncan.','Lady Macduff and her son make the cost of tyranny visible through domestic dialogue and stage violence.','Fleance escapes; the play does not show his future kingship.')]),
m('02-power-and-guilt','Power, violence & guilt',['Gain the crown','Pay the price','Judge the outcome'],[
p('Ambition with awareness','Macbeth knows duties as relative, subject and host. “Vaulting ambition” (1.7) pictures overreaching and a fall.','His hesitation establishes responsibility: he understands objections before choosing the crime.'),
p('Violence escalates','Defends Scotland → murders a sleeping guest → hires Banquo’s killers → attacks Macduff’s family.','Violence changes from public service to private security and then cruelty.','Fear does not excuse the decisions it helps explain.'),
p('Blood changes meaning','Early blood proves bravery. After Duncan’s murder it becomes evidence and moral contamination.','“Neptune’s ocean” (2.2): hyperbole makes guilt seem impossible to cleanse. Macbeth imagines staining the sea.'),
p('Sleep & washing','Murdering sleep suggests destroying innocence and peace. Lady Macbeth’s confident “little water” fails in the long term.','Repeated hand-rubbing in 5.1 makes inner guilt visible. Her command cannot remove an imagined stain.','Link the early claim to its later reversal.'),
p('Kingship vs tyranny','Duncan rewards others; Macbeth protects himself by attacking them. “Fruitless crown” (3.1) shows insecurity.','Scotland suffers beyond the palace. Malcolm’s return contrasts national recovery with Macbeth’s isolation.'),
p('A tragic ending','“Life’s but a walking shadow” (5.5) empties life of substance; power has not brought meaning.','Macbeth still fights, but courage cannot cancel murder. Lady Macbeth’s reported death limits what the audience knows.','An audience can feel horror, pity and relief together.')]),
m('03-deception-and-gender','Deception, fate & gender',['Question appearances','Weigh responsibility','Compare courage'],[
p('Fair and foul','Witches join opposites in 1.1, unsettling certainty. Lady Macbeth separates an “innocent flower” from a hidden “serpent” (1.5).','Duncan trusts the castle’s welcome while the audience knows the murder plan: dramatic irony.'),
p('Private thought, public mask','Asides and soliloquies let us hear what Macbeth conceals. At the banquet, his reactions undermine the image of a secure king.','Ask who knows what at each moment and how that changes audience tension.'),
p('Predictions are equivocal','Macbeth hears safety in promises with unexpected meanings. Branch-carrying soldiers make Birnam Wood seem to move.','Macduff’s unusual birth defeats Macbeth’s interpretation of “woman born”.','Partial truth encourages false certainty.'),
p('Choice remains visible','Witches tempt, but Macbeth plans and acts. Banquo hears prophecy too and responds more cautiously.','Dagger vision can show intention and fear. The ghost may suggest guilt, supernatural punishment or both.','Support an interpretation with stage action and language.'),
p('Competing ideas of manhood','Lady Macbeth links courage to murder. Macbeth initially insists on moral limits to manhood.','He later questions the murderers’ masculinity, repeating her tactic.','Macduff insists grief is human and compatible with courage.'),
p('Avoid simple labels','Lady Macbeth’s influence changes; she does not control every later crime. Banquo is cautious, but interested in his future.','Historical beliefs can illuminate kingship, witchcraft and gender; audiences need not respond identically.','Distinguish Scotland in the story from Shakespeare’s stage audience.')]),
m('04-drama-and-exam-writing','Drama & exam writing',['Notice the stage','Build close analysis','Develop an argument'],[
p('What an audience knows','Soliloquy: private thoughts. Aside: concealed from other characters. Dramatic irony: audience knows what a character does not.','Track contrasts between public behaviour and private speech, rather than treating the play as a novel.'),
p('How the action is staged','Duncan’s murder is offstage: anticipation and aftermath dominate. Macduff’s family faces violence onstage.','Knocking interrupts the murder aftermath. Banquet shifts from ceremony to chaos.','Explain why the order and staging matter.'),
p('Sound, form & imagery','Much speech is blank verse; rhythmic patterns can vary. Witches’ rhyme can sound ritual-like.','Lady Macbeth’s fragmented sleepwalking prose contrasts with earlier control.','Blood, sleep, darkness and clothing develop repeated ideas; explain effects, not just technique names.'),
p('15-mark extract','About 20 minutes. Give a clear overview, then follow changes across the printed passage.','Short evidence → precise word/action analysis → meaning → possible audience response.','Keep focus on this passage; avoid retelling the whole play.'),
p('25-mark essay','About 40 minutes. 20 literary marks + 5 for writing accuracy. Plan a clear answer and three/four developing moments.','Link beginning, middle and end; show how Shakespeare presents the idea.','Use connected paragraphs and accurate quotation or clear event references.'),
p('Flexible evidence','“Vaulting ambition”: excess and judgement. “Fruitless crown”: insecurity. “Little water” → “damned spot”: reversal and guilt.','“Feel it as a man”: grief and courage. “Walking shadow”: emptiness.','Explain evidence in its moment, then link it to the argument.')]) ]}

for item, panel, kind, height in [(MAPS[1][0],1,"lit-downfall",125),(MAPS[1][1],2,"lit-partnership",95),(MAPS[1][2],2,"lit-guilt",95),(MAPS[1][3],0,"lit-irony",110),(MAPS[1][4],0,"lit-irony",110)]:
 item["pics"][panel]=(kind,height)

from literature_poetry_maps import MAPS as POETRY_MAPS
MAPS[2]=POETRY_MAPS
