"""All 15 current poems, with short quotation anchors and original analysis."""
from literature_qa_writer import q,write_bank
ANTHOLOGY='../../00 - Specification/Eduqas-poetry-anthology-first-assessment-2027.pdf'
items=[]
def single(title,poet,page,focus,answer):
 prompt=f'Read [{title}]({ANTHOLOGY}#page={page}) by {poet}. How does the poet present {focus}? Refer to language, form, structure and relevant context.'
 items.append(q(15,prompt,answer,'Current 2027 anthology: '+title+'; single-poem format verified in 2019/2023/2024 Q71'))

single('The Schoolboy','William Blake',6,'the child’s experience of growing up', '''Blake presents childhood as a period of natural energy that can be damaged by fearful adult control. The child's unhappiness at school is therefore more than a complaint about an unpleasant day: it raises a question about future development.

The opening birdsong makes the child part of a lively outdoor world. The transition to school removes that sense of company. The “cruel eye” reduces authority to a threatening gaze, suggesting that being watched replaces the freedom to explore. Blake's interest in childhood and his resistance to restrictive institutions help explain why the poem gives the child a challenging voice.

The **extended metaphor** of a bird in a cage makes the argument concrete. Singing is natural to the bird, but confinement prevents it. Similarly, a child's curiosity cannot flourish when fear dominates the day. The question challenges adults to explain a system that obstructs the very growth it should support.

The later plant images extend the problem through time. Damaged buds cannot produce the expected fruit. By addressing parents, the speaker connects present treatment with adult responsibility for what follows.

The six patterned stanzas retain something of a song, but their repeated questions make that song increasingly urgent. The poem ends by asking about consequences rather than reassuring the reader. Blake presents healthy growth as something adults must protect, not something they can safely force through restriction.''')
single('I Wandered Lonely as a Cloud','William Wordsworth',8,'the effects of nature', '''Wordsworth presents nature as a source of companionship whose value continues through memory. The encounter changes both the speaker's mood during the walk and his later experience of being alone.

The opening cloud **simile** suggests movement and distance. The speaker wanders without an obvious companion, but the daffodils appear as a “crowd”. This social word turns flowers into company. Their dancing movement gives the landscape energy and makes the speaker seem included in a shared pleasure.

The comparison with stars greatly enlarges the scene. The flowers appear plentiful and almost limitless, encouraging wonder rather than a narrow description of a few plants. Repeated dancing imagery connects the waves, flowers and eventually the heart.

The final stanza changes the time and location. The speaker is now on his couch, and the “inward eye” returns him to the scene. This **metaphor** identifies imagination as the means by which an external experience becomes an internal resource. He did not fully understand its value at the time.

Four regular six-line stanzas and the closing couplet help the poem arrive at satisfaction. Its movement from loneliness to pleasurable solitude reflects Romantic interest in nature, individual feeling and imagination. The ending does not merely repeat the start: being alone has become enjoyable because recollection supplies company and emotional richness.''')
single('Sonnet 29','Elizabeth Barrett Browning',13,'longing for a loved person', '''Barrett Browning presents longing as energetic and imaginative, but ultimately insufficient without the beloved's presence. The speaker values the real person more highly than the thoughts generated by absence.

The **extended metaphor** of vines around a tree initially suggests flourishing love. Thoughts grow and spread, giving desire a living form. Yet their abundance becomes a problem when the greenery hides the wood. Imagination can obscure the person it is supposed to celebrate.

The early turn beginning “Yet” changes the direction of the argument. The speaker refuses to accept thoughts as a replacement. “Renew thy presence” is a forceful imperative, so she is not simply a passive admirer waiting quietly. She openly asks for the relationship she wants.

The imagined breaking and falling of the vines makes presence feel like liberation. Seeing, hearing and breathing replace an experience dominated by thought. The poem develops from mental elaboration towards direct, physical nearness.

The **sonnet form** connects the poem with a long tradition of concentrated love poetry. However, the turn does not wait neatly for the conventional octave–sestet boundary; the argument starts changing earlier. The ending reverses the opening emphasis on thinking.

Its place in Sonnets from the Portuguese, associated with love for Robert Browning, helps explain the personal urgency of this female voice. The final ideal is not endless fantasy but a closeness in which fantasy is no longer needed.''')
single('Cousin Kate','Christina Rossetti',10,'power in relationships', '''Rossetti presents power as unequal but capable of being challenged through speech and motherhood. The abandoned speaker begins with a story of exploitation, then forces a reassessment of who possesses something valuable.

The lord's status allows him to move the speaker from her cottage into his world and then discard her. The **simile** “changed me like a glove” turns a person into something replaceable. It exposes the imbalance between his freedom to choose and her vulnerability to the consequences.

Direct address makes Kate the immediate target of the speaker's anger. Repeated contrasts between their positions connect material wealth with public approval. Victorian expectations of sexual respectability explain why marriage protects Kate while the unmarried speaker becomes an outcast. The man who helped create this situation faces much less visible judgement.

However, the speaker refuses to accept that reputation proves moral superiority. Her claim that she would have rejected the lord in Kate's position challenges Kate's loyalty. Because this is one woman's account, readers should notice its persuasive force rather than assume access to Kate's inner motives.

The final stanza reveals the son. “My shame, my pride” places social condemnation beside maternal affection, and the prospect of inheritance gives the child significance to the lord. The delayed revelation changes the apparent balance of power.

The patterned storytelling therefore leads to resistance, not complete defeat. Rossetti gives a socially marginalised woman the voice to question the values used against her.''')
single('Drummer Hodge','Thomas Hardy',14,'the loss caused by war', '''Hardy presents war through the loss of an ordinary young person, concentrating on displacement and an inadequate burial rather than battlefield glory. Naming Hodge gives attention to someone who might otherwise disappear into a casualty total.

The opening verb “throw” makes the burial sound hurried and impersonal. “Uncoffined” emphasises the absence of a familiar sign of care. These details challenge any expectation that military death will necessarily bring honour or ceremony.

The landscape then becomes central. Local terms and unfamiliar constellations suggest a place Hodge never had time to understand. Remembering his Wessex home makes the distance emotional as well as geographical. The Second Boer War setting explains how a young English drummer could die in southern Africa, while Hardy focuses on the personal cost of that imperial conflict.

The three six-line stanzas move through present burial, past origins and future incorporation into the land. Their regular rhyme gives a lasting order to a life whose ending was abrupt. It is as though the poem supplies some of the attention missing from the burial.

In the final stanza, the possibility of becoming part of a tree offers natural continuity. However, “for ever” also makes separation permanent. This is not a return to the home he knew. Hardy allows connection with nature to coexist with the irreversible loss of a young life, leaving readers with a restrained rather than triumphant ending.''')
single('Disabled','Wilfred Owen',16,'the consequences of war', '''Owen presents war as a rupture between a young man's expectations and his dependent, neglected present. Injury matters, but the poem also exposes the social response that deepens his isolation.

The “ghastly suit of grey” makes the opening scene colourless and deathlike. Memories of lively evenings and attractive surroundings create a sharp **contrast**. The world can still be pleasurable for others, making his sense of exclusion more painful.

The account of enlistment challenges a heroic explanation. Uniforms, admiration and sport have more place in his thinking than a considered political cause. The accepted age claim suggests that those recruiting him did not protect him adequately. In the context of the First World War, Owen questions the glamour and social pressure surrounding military service.

Blood also changes meaning. In football it once brought admiration; in battle its loss causes devastating harm. This reversal undermines the idea that war is simply a grander form of sporting competition.

The movement between past and present prevents a smooth progress narrative. Each attractive memory makes the current circumstances harder to bear. The weak welcome home exposes the difference between public enthusiasm for enlistment and practical care for a survivor.

The repeated question at the end leaves him waiting for assistance. Owen withholds comforting closure, directing attention towards an unmet need. The criticism concerns this man's experience and society's treatment of him; it does not require readers to treat disability itself as the loss of human value.''')
single('I Shall Return','Claude McKay',19,'feelings about home', '''McKay presents home as a precious source of identity and hoped-for relief. The speaker's confidence in returning is strong, but the final admission of pain shows why that confidence needs to be repeatedly voiced.

The repeated promise “I shall return” creates determination. Because the return remains in the future, repetition can also sound like self-reassurance. The poem lets certainty of desire coexist with uncertainty about fulfilment.

The colours “golden” and “sapphire” make remembered scenery valuable as well as vivid. The speaker does not list neutral geographical facts: the landscape is filtered through affection. The streams and grasses suggest a living world in which the person longs to participate again.

The poem then moves from nature towards village music and community. “Delicious tunes” blends sound with taste, suggesting that cultural experience can nourish. Home means shared life, not just an attractive view.

The **Shakespearean sonnet** gives the thought three developing quatrains and a final couplet. That ending reveals the painful separation behind the earlier richness. The promise of return becomes an answer to emotional need.

McKay's migration from Jamaica and association with the Harlem Renaissance make cultural attachment and displacement relevant contexts. They illuminate the speaker's investment in a homeland without requiring every detail to be a literal autobiography. The poem ends with a desired future, not evidence that the journey has already happened.''')
single('Decomposition','Zulfikar Ghose',20,'attitudes towards suffering', '''Ghose presents a change from detached visual interest to uncomfortable self-criticism. The speaker learns that making a striking image and responding humanely to its subject are not the same achievement.

Initially, the sleeping man's body seems to merge with the pavement. The **metaphor** “fossil man” makes him appear fixed within stone, suggesting both long neglect and a loss of individuality. Yet it also reveals the photographer's way of looking: a living person has become a shape in a composition.

The surrounding crowd watches entertainment rather than the beggar. This contrast suggests that familiarity can make hardship easy to overlook. The busy Bombay setting makes suffering public without making it the centre of public attention.

The speaker is not allowed to remain morally separate from that crowd. His earlier satisfaction with the photograph and its clever caption become part of the problem. “Glibly” judges his former response as too easy and superficial. The poem turns the observer into somebody who must also be examined.

Five quatrains in free verse move from description towards reflection. The late shift from past confidence to present shame changes what the reader is asked to value. Technical success as an image-maker no longer settles the ethical question.

The ending places the man's hardship above the photographer's artistic pride. Ghose therefore explores responsibility in representation: a vulnerable person should not disappear behind the observer's cleverness. The title does not establish that the sleeping man is dead.''')
single('Catrin','Gillian Clarke',22,'the mother–daughter relationship', '''Clarke presents the relationship as a continuing negotiation between attachment and independence. The mother's love does not remove conflict; it helps explain why separation feels so intense.

The remembered birth introduces a struggle in which both mother and child seek to become separate. The **metaphor** “Red rope of love” evokes the umbilical cord while giving the bond emotional force. Its colour links affection with the bodily intensity of childbirth. Connection can sustain people and also make letting go difficult.

The clinical room contrasts with the mother's expressive experience. Clean geometric surroundings cannot contain the feelings she imagines writing across them. This gives a woman's embodied experience a strong voice within a setting designed for order.

The second stanza moves to a later disagreement. The daughter now wants freedom to skate in the dark, so an ordinary family moment repeats the earlier problem in a new form. The cord is no longer physically present, but the metaphorical bond still pulls.

The two unequal stanzas therefore connect experiences across years. **Enjambment** carries feeling over line boundaries, while the repeated rope image prevents the time shift from becoming a complete break. Clarke's experience of motherhood provides a relevant context for the intimate direct address.

The ending does not announce a winner. Instead, it shows that growth requires continuing adjustment. The poem recognises both the child's desire to become independent and the mother's difficulty in loosening a deeply felt connection.''')
single('Blackberry Picking','Seamus Heaney',24,'disappointment', '''Heaney presents disappointment as the collision between intense desire and an outcome the speaker cannot control. The remembered experience becomes a pattern in which knowledge does not entirely extinguish hope.

At first, sensory detail makes the fruit powerfully attractive. Taste, colour and texture explain why collecting becomes urgent. The rural containers and fields root the memory in an ordinary childhood activity rather than an abstract lesson. Heaney's Northern Irish upbringing helps account for this precise physical setting.

However, disturbing images complicate the pleasure even before the berries rot. Bloodlike colour, watching eyes and the Bluebeard allusion suggest that greed and unease accompany enjoyment. The desire to gather everything already risks turning appreciation into possession.

The **stanza break** marks a decisive change. The longer opening section accumulates excitement, while the shorter second section exposes the failure of storage. Sweetness gives way to unpleasant smell and decay. The sensory language that attracted the reader now produces revulsion.

At the end, “hoped” and “knew” create a compact conflict between feeling and understanding. The speaker recognises the inevitable outcome but repeats the emotional investment each year. This prevents the poem from becoming a simple story of learning a lesson once.

The adult recollection preserves the experience in language even though the child could not preserve the fruit. Heaney makes disappointment part of a broader encounter with time, desire and the limits of keeping what we love.''')
single('Kamikaze','Beatrice Garland',26,'conflict between personal life and duty', '''Garland presents a conflict in which survival itself becomes grounds for punishment. The pilot returns from a mission that expects his death, but the community's response makes continued life socially painful.

The ceremonial details at departure connect his personal journey with military honour. Against this, the sea's movement, colours and abundance make ordinary living attractive. The remembered fishing expeditions centre on a father's safe return, quietly opposing the demand that this father should not come back.

However, the account does not give direct access to his mind. “She thought” marks the daughter's reconstruction. This **qualified narration** matters because the family's later silence may prevent a fully shared explanation. The reader experiences the gap between what can be imagined and what was actually communicated.

The return changes the poem's focus from natural richness to human exclusion. Children initially retain affection, then learn the silence of the adults. Rejection is presented as a social practice that can be passed on, not simply an instinctive response.

The seven six-line stanzas give the narrative a visible pattern, while shifting voices and flowing sentences complicate who controls the story. The Second World War kamikaze context explains the pressure to sacrifice an individual life for a national cause.

The final imagined question leaves physical death and social erasure in painful tension. Garland does not resolve the pilot's thoughts for us. Instead, the poem asks readers to consider what a system of honour costs the families expected to enforce it.''')
single('War Photographer','Carol Ann Duffy',29,'responses to the suffering of others', '''Duffy contrasts the photographer's lasting involvement with the limited response of distant spectators. The process of producing a photograph becomes a way of examining what people do with another person's pain.

In the darkroom, the photographer arranges his work in “ordered rows”. The phrase suggests professional control, but what he orders represents disorder and suffering elsewhere. The religious comparison with a “priest” makes the task solemn, as though the images demand respectful attention rather than casual consumption.

His delayed trembling shows that professional steadiness in danger does not remove emotional consequences. The contrast between home comforts and threatening foreign ground further separates the experience of witnessing from the safety of looking at a newspaper.

As a face emerges in the developing image, a particular memory returns. The poem moves from organised material towards an individual human loss, resisting the reduction of suffering to anonymous numbers.

Four regular sestets and their rhyme pattern create a formal order beside this disturbance. The film darkroom and newspaper-supplement setting also makes selection important: the editor can publish only a small number of images, and readers may pause briefly before resuming ordinary pleasure.

The ending sends the photographer back towards work, suggesting a cycle rather than resolution. Duffy questions a culture in which images circulate widely but compassion may remain short-lived. The photographer is not simply emotionless; his outward discipline and inner distress are deliberately held together.''')
single('Dusting the Phone','Jackie Kay',31,'the effects of uncertain love', '''Kay presents uncertain love as a state in which imagination increases anxiety rather than providing comfort. The speaker can recognise the problem but cannot easily step outside it.

The opening sets worrying against the possibility of remembering happy moments. This self-awareness makes the voice recognisable: knowing that a habit is unhelpful does not stop it. Both a ringing phone and a silent phone then become evidence of disaster. The repeated “Sirens” gives ordinary domestic experience the sound of an emergency.

Possible futures accumulate without settling into one likely outcome. The list creates emotional instability because security and loneliness remain equally imaginable. Meanwhile, the absent lover's instruction to avoid discussing love makes the imbalance in their needs visible.

The **personified telephone** becomes an object to serve. Polishing and dressing for it suggest the speaker is trying to purchase a response through good behaviour. The exaggeration can be comic, but it also shows the loss of ordinary control over the day.

Free verse allows the sentences to change length and direction. The sequence of tercets is finally broken by an isolated last line, after the speaker's attempted threat falls apart. That structural deflation makes the ending uncertain rather than triumphant.

The domestic telephone places the poem within recognisable modern communication habits. Kay turns an everyday object into a means of exploring dependence, showing how desired connection can become a source of isolation.''')
single('Remains','Simon Armitage',33,'the lasting effects of violence', '''Armitage presents violence as an event that continues inside the survivor after its outward action has ended. The soldier's changing voice reveals both traumatic memory and unresolved responsibility.

The colloquial opening makes the patrol sound like another episode in a longer conversation. However, “probably armed, possibly not” introduces a doubt that the speaker cannot settle. The uncertainty matters morally because it concerns the threat posed by the person who is shot.

The account moves from shared action to intensely visual bodily damage. This shift prevents the reader from accepting the shooting as merely routine. The **compound image** “blood-shadow” then joins a physical trace to a haunting presence: removal of the body has not removed the event.

Returning home fails to create a clean boundary. Blinking and sleeping bring the scene back, while military imagery makes the mind itself seem occupied. The battlefield has become an internal space. Armitage's work with veterans' testimony provides a context for this attention to suffering after service.

The dramatic monologue lets the soldier's own speech carry the disturbance. Early references to the group narrow towards a more isolated sense of responsibility. The short final couplet concentrates the ending on what remains personally inescapable.

The poem therefore resists a simple finished-action story. Its speaker can leave the location but cannot resolve the doubt or stop the replay. The poem does not confirm whether the looter was armed; its emotional force depends on that uncertainty remaining open.''')
single('Origin Story','Eve L. Ewing',35,'the value of family relationships', '''Ewing presents family value as something that can survive the ending of a romantic relationship. The speaker looks closely at an imperfect past without dismissing either the love or the identity that came from it.

The opening details give the parents separate young lives before they meet. Their clothes, interests and movement through Chicago make them particular people rather than idealised parental figures. The comic book involved in the meeting then provides the poem's central comparison.

“Love is paper” makes affection fragile and material. The **extended metaphor** allows the speaker to compare careful preservation with the damage caused by ordinary handling. Protecting a comic might keep it intact, but repeated reading can also show that it has been enjoyed intensely.

The second stanza therefore complicates the obvious lesson that all damage proves failure. Its list of uses makes the relationship seem lived in, not merely neglected. The reader has to consider different meanings of care and value.

Two unequal free-verse stanzas move from narrative into reflection. The title echoes a superhero backstory, giving an ordinary family's history imaginative importance. Ewing's Chicago and Black family context helps explain the significance of recording these personal origins.

The final “good ending” invites readers to connect the relationship with the speaker herself. The romance may not have lasted, but its consequences cannot be measured only by permanence. Ewing ends with an affectionate reassessment rather than a demand for a flawless family story.''')

def comparison(first,page,focus,answer,ref):
 prompt=f'Read [{first}]({ANTHOLOGY}#page={page}). Choose one other poem from the anthology that explores {focus}. Compare how the poets present {focus}, considering content, language, form, structure and relevant contexts.'
 items.append(q(25,prompt,answer,ref+'; original task using the current 2027 anthology'))

comparison('I Wandered Lonely as a Cloud',8,'experiences of nature', '''Wordsworth's I Wandered Lonely as a Cloud and Heaney's Blackberry Picking both make nature emotionally powerful, but they differ over how pleasure can last. Wordsworth finds an enduring resource in recollection; Heaney exposes the failure of trying to keep a physical possession unchanged.

Both poets initially make the natural world inviting. Wordsworth's personified flowers form lively company for a solitary walker. Heaney's sensory descriptions make the berries attractive enough to provoke urgent collecting. However, the responses already differ: Wordsworth watches, whereas Heaney's children gather and hoard. One experience centres on attention; the other develops into an attempt at possession.

The imagery also qualifies their pleasure differently. Wordsworth's repeated dancing links landscape and emotion, culminating in movement within the heart. Heaney places unsettling associations of blood and watching eyes among the attractive details. These images suggest that appetite is not entirely innocent, even before the fruit decays.

Their structural turns make the contrast decisive. Wordsworth's final stanza moves to the couch, where absence from the landscape does not prevent its benefit. The “inward eye” makes memory sufficient. Heaney's second stanza reveals the stored fruit deteriorating, and the closing opposition between “hoped” and “knew” leaves emotional desire in conflict with understanding. His ending acknowledges repetition without promising escape from disappointment.

The contexts help explain these different emphases. Wordsworth's Romantic interest in imagination gives recollection a restorative force. Heaney's remembered rural childhood gives desire a physical setting of fields, containers and storage. The adult speaker can preserve the experience in a poem, but that does not mean the child succeeded in preserving the berries.

Both poems therefore value close attention to ordinary nature. Their difference lies in the kind of permanence available: Wordsworth celebrates an emotional afterlife, while Heaney shows that the material source of pleasure remains vulnerable to time.''','2019 Q71–72 loss and 2023 Q71–72 place demonstrate thematic analysis/comparison format'),
comparison('Sonnet 29',13,'longing in a relationship', '''Barrett Browning's Sonnet 29 and Kay's Dusting the Phone both show absence making thought intense. Yet Browning develops an imagined release through closeness, while Kay leaves the speaker caught in uncertainty.

Both turn an emotional experience into something tangible. In Sonnet 29, thoughts become vines around the beloved tree. Growth communicates the energy of desire, but excessive growth hides the person. In Dusting the Phone, a domestic device becomes the focus of service and attention. The speaker treats it as though it could reward devotion with the wanted call. Both images show a substitute threatening to dominate the relationship it represents.

The speakers also try to assert control. Browning's imperative “Renew thy presence” identifies what would satisfy her: the real person must displace the imagined version. Kay's speaker recognises the anxiety of waiting but cannot settle it. The repeated “Sirens” makes ringing and silence equally threatening, so there is no ordinary outcome that feels safe.

Form and structure sharpen the difference. Browning uses a traditional sonnet while beginning the turn early. Her argument develops towards an ending that reverses the opening emphasis on thought. Kay's free verse permits conversational fragments and sudden changes of direction. The isolated final line undercuts the attempted ultimatum instead of resolving the wait.

Their contexts support these choices. Browning's poem belongs to a love-sonnet sequence associated with Robert Browning and gives a female speaker an active language of desire. Kay examines intimacy through a modern household telephone, making dependence visible in familiar behaviour. Neither context removes the need to analyse the particular voice rather than assume a complete autobiography.

Both poems insist that imagined contact is insufficient. The significant difference is the speaker's final position: Browning can envision presence overcoming thought, whereas Kay dramatises a need that remains unanswered.''','2024 Q71–72 relationship theme and comparison format'),
comparison('The Schoolboy',6,'freedom and restriction', '''Blake's The Schoolboy and Clarke's Catrin both connect growing up with a struggle for freedom. Blake foregrounds a child's protest against damaging authority, while Clarke explores the emotional difficulty of loosening a loving bond.

Their speaking positions are crucial. Blake lets the unhappy child challenge adults directly. The “cruel eye” makes authority feel impersonal and threatening, so readers are encouraged to question the conditions imposed on the child. Clarke speaks as a mother remembering childbirth and a later disagreement. Her viewpoint gives the protective adult an inner life as well as acknowledging the daughter's demand for independence.

Both use extended images to make restriction visible. Blake's caged bird cannot express its natural joy. The image suggests that confinement defeats healthy development. Clarke's “Red rope of love” evokes a bond that both connects and pulls. Unlike the cage, the rope carries affection as well as pressure, so the relationship is not simply an opposition between cruelty and freedom.

The movement through time also differs. Blake turns from one unhappy school day towards the consequences of damaged buds and future seasons. Present restriction threatens what the child could become. Clarke's two stanzas link physical separation at birth with a later request to skate after dark. The struggle has changed form but has not vanished.

These choices fit their contexts. Blake's concern with childhood and restrictive institutions gives the poem a protesting force. Clarke makes a mother's bodily and emotional experience worthy of sustained attention, complicating any easy assumption that family authority is either wholly right or wholly oppressive.

Neither ending supplies a neat settlement. Blake's questions demand that adults rethink their treatment of children. Clarke's ordinary final request reveals that independence must be negotiated repeatedly. Both value growth, but Clarke more strongly holds the desire for freedom beside the continuing need for connection.''','Additional thematic comparison using verified Q72 format'),
comparison('Disabled',16,'isolation after military service', '''Owen's Disabled and Garland's Kamikaze present homecoming as something more difficult than physical return. Both expose a gap between the value society claims to place on military service and its treatment of a person who returns outside the expected heroic pattern.

In Disabled, the veteran's present is set against memories of sport, attraction and public applause. The “ghastly suit of grey” contrasts with the colour of earlier life. People who once encouraged enlistment offer little meaningful support afterwards. Kamikaze instead presents a physically surviving pilot whose decision not to complete a suicide mission leads to deliberate silence. The forms of isolation differ: neglect surrounding injury in Owen, and enforced exclusion in Garland.

Both poems show how public expectations enter personal relationships. Owen's character recalls reasons for joining connected with appearance and admiration. Garland's children initially continue ordinary affection, then learn the adults' rejection. Social values are therefore not remote ideas: they alter how bodies are welcomed, touched, addressed or ignored.

Their narrative structures complicate simple judgement. Owen repeatedly interrupts the present with the past, making lost possibilities remain painfully active. Garland uses the daughter's reconstruction, qualified by “she thought”, so readers cannot treat the pilot's motives as a direct confession. The missing explanation itself reflects broken family communication.

The First World War background of Disabled helps expose the distance between recruitment glamour and care for survivors. The Second World War kamikaze setting makes national duty demand death, so the pilot's return can be interpreted as dishonour by those around him. Neither poem requires us to approve the standards it depicts.

At the end, Owen leaves the veteran waiting for practical help; Garland leaves an imagined question about different forms of death. Both withhold comforting reintegration. Survival is real, but society's response can prevent it from becoming a restored life.''','2019 Q71–72 loss; additional comparison with current poems'),
comparison('Remains',33,'the lasting effects of conflict', '''Armitage's Remains and Duffy's War Photographer both show conflict continuing beyond the place where violence occurred. Their central figures return home, but memory prevents that geographical movement from becoming psychological escape.

The difference in responsibility shapes each poem. The speaker in Remains participated in a shooting and remains uncertain about the threat posed by the victim. The photographer witnesses and records suffering, then faces questions about representing it and communicating it to others. Both carry distress, but the soldier's doubt concerns his own violent action more directly.

Armitage makes the past return through ordinary acts such as blinking and sleeping. Military imagery then relocates the battlefield inside the mind. Duffy connects a photograph's gradual development with a human face returning to memory. In each case, the poet makes recollection an event happening now rather than a safely distant description.

Their forms reflect different attempts to contain the experience. Remains uses colloquial dramatic monologue, drawing readers into an apparently informal account before exposing its unresolved pain. Its ending narrows towards personal responsibility. War Photographer uses regular sestets and rhyme; the “ordered rows” parallel a professional effort to organise material that represents chaos. Formal order does not prove emotional calm.

The contexts reinforce the distinction. Armitage's engagement with veterans' accounts draws attention to harm after military service. Duffy's film darkroom and newspaper culture reveal a chain from witness to editor to reader, raising the question of whether recording pain produces lasting concern.

Both endings resist closure. The soldier cannot remove the memory, while the photographer returns to a cycle of work and limited public response. The poems suggest that coming home can expose the continuing effects of conflict more clearly, because outward safety contrasts with an experience that remains inwardly active.''','Additional trauma comparison; thematic Q72 format verified in all sampled papers'),
comparison('Decomposition',20,'responses to images of suffering', '''Ghose's Decomposition and Duffy's War Photographer both question what happens when suffering becomes an image. They agree that seeing a photograph is not automatically the same as responding responsibly, but direct their criticism towards different points in the process.

Ghose's speaker begins by describing a sleeping beggar as a striking visual subject. The “fossil man” metaphor merges body and pavement, making neglect visible while also exposing how the observer reduces a person to a pattern. Duffy initially presents the photographer's work as solemn. The comparison with a priest suggests an obligation to attend carefully to human pain rather than merely produce an attractive composition.

Both include spectators whose attention is inadequate. In Decomposition, the crowd prefers a street performance to the beggar's familiar hardship. In War Photographer, readers briefly respond before returning to comfortable routines. The shared problem is selective attention: suffering is available to be seen but does not necessarily interrupt ordinary priorities.

However, the photographers occupy different moral positions. Ghose's speaker turns criticism on himself. His former satisfaction becomes shame when he recognises the presumption of making art from another person's hardship. Duffy gives the photographer delayed distress and a serious purpose, while exposing the limits imposed by editorial selection and public indifference. He is not simply outside the ethical problem, but neither is he presented as a straightforward exploiter.

The structures carry these developments. Ghose moves from a past photograph towards present self-judgement in five free-verse quatrains. Duffy's regular stanzas follow work, memory and publication before returning to another departure. One ending changes the speaker's understanding; the other emphasises a recurring professional cycle.

The urban Bombay scene and the newspaper darkroom both place a camera between vulnerable subjects and more powerful observers. Ultimately, both poems ask what an image-maker or viewer owes to the people represented, beyond admiration of the image itself.''','2023 Q71–72 place; additional ethical comparison using current anthology'),
comparison('I Shall Return',19,'belonging to a place', '''McKay's I Shall Return and Hardy's Drummer Hodge both connect identity with landscape, but place their central figures in sharply different relationships to home. McKay's speaker imagines recovering belonging; Hodge's death makes return impossible.

McKay's remembered home is rich in valued colour. “Golden” and “sapphire” make the landscape seem precious, while streams and music suggest participation in a living community. Hardy instead emphasises unfamiliar local features and strange constellations. Hodge is surrounded by a landscape that he never learned to understand. In both poems, geography carries feeling rather than functioning as neutral scenery.

The treatment of time makes the contrast stronger. McKay's repeated “I shall return” turns memory into a future promise. The speaker draws hope from what has been lost. Hardy's three stanzas move from burial to Hodge's former home and then to his permanent place in the foreign earth. That future cannot contain reunion with Wessex.

Both poets use patterned forms to give individual feeling weight. McKay's sonnet moves from nature to communal music before the couplet reveals the pain behind the longing. Hardy's regular six-line stanzas give dignity and sustained attention to someone whose burial was hurried. Formal control does not make either separation painless.

Context illuminates why the displacements differ. McKay's migration from Jamaica and association with the Harlem Renaissance make cultural memory and attachment to a homeland significant. Hardy's Second Boer War setting shows an ordinary young person carried abroad by imperial conflict. The same distance from home can therefore involve different kinds of agency and different possibilities of return.

Hardy's final tree image suggests incorporation into another landscape, but it cannot restore Hodge's living participation in his own community. McKay preserves that possibility as a hope. Together, the poems show that belonging involves remembered relationships and meanings, not simply occupying a piece of ground.''','2023 Q71–72 place; 2019 Q71–72 loss'),
comparison('Cousin Kate',10,'family after a relationship ends', '''Rossetti's Cousin Kate and Ewing's Origin Story both resist judging a family solely by whether a romantic relationship lasts. Each finds value in the child connected with that relationship, but their speakers reach this position through different tones and arguments.

In Cousin Kate, the abandoned mother's direct address makes the poem confrontational. The lord has “changed me like a glove”, and public judgement compounds his treatment. The simile exposes her reduction to a replaceable possession. Origin Story gives the parents individual histories before their meeting, so an ended romance is approached through affectionate attention rather than primarily through accusation.

Both poems use an object comparison to explore vulnerability. Rossetti's glove suggests careless replacement by someone with power. Ewing's comic book can be damaged through mishandling, but wear may also record repeated enjoyment. Her metaphor leaves more room to value something imperfectly protected. The difference prevents broken love from becoming one simple experience shared identically by both speakers.

Their structures also reframe the past. Rossetti delays the revelation of the son until the final stanza, changing the apparent distribution of power. “My shame, my pride” brings social condemnation into direct conflict with maternal feeling. Ewing moves from the story of a meeting into reflection, then ends by inviting the reader to see the speaker herself as a valuable consequence.

The contextual pressures are different. Victorian respectability and inheritance explain why the unmarried mother faces exclusion and why a son matters to the lord. Ewing's Chicago family history gives personal and Black cultural experience a place within a contemporary poetic account of identity. Her title's comic-book association makes ordinary origins worthy of imaginative attention.

Rossetti ends with defiance against a damaging hierarchy; Ewing offers a gentler reassessment of an imperfect past. Both challenge the assumption that an ended romance leaves only failure, but only Rossetti makes that challenge a direct confrontation with public shame.''','2024 Q71–72 relationships; original comparison using the 2027 texts')

write_bank(2,'Poetry anthology',items,'June 2019, 2023 and 2024 each use Q71 for a named-poem response (15 marks) and Q72 for a comparison with a chosen anthology poem (25 marks). The sampled focuses are loss (2019), place (2023) and a relationship (2024). Each appears once in this three-paper sample; none is a prediction. Those papers assess the previous anthology. Their task structure and assessment skills inform this practice, but every question here uses the new 15-poem anthology first assessed in 2027. There are no completed 2027-series papers available at the time of preparation. The answers demonstrate one supported reading and, for comparisons, one possible second-poem choice. AO1, AO2 and AO3 apply; the extra Shakespeare writing-accuracy allocation does not apply to these poetry questions.')
