"""Related-poem maps: meaningful comparisons without shrinking A4 text."""
from biology_course_maps import p,m
MAPS=[
m('00-anthology-overview','Poetry anthology',['Experience & memory','Relationships & identity','Conflict & judgement'],[
p('Nature and childhood','**The Schoolboy:** fear restricts natural growth. **Wordsworth:** remembered nature restores joy. **Blackberry Picking:** desired pleasure gives way to decay.','Compare who or what causes change: authority, recollection or time.'),
p('Home and the past','**I Shall Return:** homeland remembered; return hoped for. **Drummer Hodge:** burial abroad makes separation permanent.','Place can preserve identity or expose distance from it. Compare the endings, not just landscape words.'),
p('Love and distance','**Sonnet 29:** thoughts must give way to the real beloved. **Dusting the Phone:** imagined contact becomes anxious dependence.','**Cousin Kate:** rejection and public judgement meet maternal pride. Compare power and the speaker’s final position.'),
p('Family and selfhood','**Catrin:** connection survives conflict over independence. **Origin Story:** imperfect parental love can leave a valuable legacy.','Both look back, but from different generations. A shared theme does not mean the same attitude.'),
p('War beyond the battlefield','**Disabled:** injury and neglected homecoming. **Kamikaze:** survival followed by exclusion. **Remains:** a violent event persists in memory.','Distinguish physical loss, social punishment and psychological harm.'),
p('Looking and responsibility','**War Photographer:** witness, editor and audience respond differently. **Decomposition:** an observer rethinks making art from hardship.','For every poem: voice → changing ideas → language/form/structure → relevant context. Compare effects with evidence.')]),
m('01-nature-and-childhood','Nature & childhood',['Freedom can be damaged','Pleasure can return','Pleasure can decay'],[
p('The Schoolboy: meaning','Blake’s child enjoys nature but suffers under fearful schooling. Bird-in-cage and damaged-plant images link restriction to lost development.','**Cruel eye:** authority becomes surveillance. Appeals to parents make adults responsible for the future.'),
p('Blake: how it works','Six five-line stanzas; songlike pattern contrasts with confinement. Questions demand an answer rather than accepting adult power.','Context: childhood and resistance to restrictive authority. Compare Catrin’s mother–child conflict.'),
p('Wordsworth: meaning','A solitary walker finds company in dancing daffodils. Later, the **inward eye** brings the scene back.','Personification moves the flowers’ dance into the heart. The gain is emotional wealth.'),
p('Wordsworth: how it works','Four six-line stanzas, ABABCC. Final stanza shifts from past encounter to recurring present pleasure.','Romantic nature, imagination and personal feeling. Solitude becomes rewarding, unlike the opening loneliness.'),
p('Blackberry Picking: meaning','Heaney’s remembered childhood moves from eager collecting to rotten fruit. Sensory attraction becomes disgust.','Blood, eyes and Bluebeard imagery add unease. Desire outlasts knowledge of inevitable decay.'),
p('Heaney: how it works','Long first stanza gathers excitement; shorter second stanza reverses it. Rural Northern Irish childhood informs concrete details.','Compare: Wordsworth preserves pleasure through memory; Heaney cannot preserve fruit. Blake blames restriction, not natural decay.')]),
m('02-love-and-absence','Love & absence',['Thoughts seek presence','Waiting deepens distress','Compare the resolution'],[
p('Sonnet 29: the idea','Barrett Browning’s thoughts resemble vines growing around the beloved tree. They express desire but can hide the real person.','The speaker wants actual presence. Commands make her an active voice in love.'),
p('Sonnet 29: the method','A **Petrarchan sonnet**: 14 lines. Early turn with Yet starts rejecting thought as a substitute. Ending reverses the opening.','Natural growth becomes release as greenery falls. Context: Sonnets from the Portuguese and love for Robert Browning.'),
p('Dusting the Phone: the idea','Kay’s speaker fears disaster whether the telephone rings or stays silent. Every outcome feeds uncertainty.','Polishing and dressing for the personified phone suggest service to an object that controls the day.'),
p('Dusting: the method','Free verse and tercets lead to an isolated last line. Fragments and questions interrupt attempts at control.','Modern domestic communication makes dependence concrete. The lover’s gender is not specified; the speaker is not automatically the poet.'),
p('A shared problem','Absence makes imagination powerful. Browning uses a growing plant; Kay uses a household device.','Both speakers address a beloved and want more than imagined contact. Compare how desire is voiced.'),
p('A different ending','Browning imagines closeness freeing her from thought. Kay’s attempted ultimatum collapses into uncertainty.','Build an argument about **control**, then connect metaphor, changing tone and ending. Do not give two separate summaries.')]),
m('03-family-and-identity','Family & identity',['Challenge social judgement','Negotiate independence','Revalue an imperfect past'],[
p('Cousin Kate: the idea','Rossetti’s abandoned speaker addresses the cousin who married the lord. The son gives her a final source of pride and power.','Glove simile exposes disposability. Direct address makes her account angry and persuasive.'),
p('Cousin Kate: the method','Six eight-line stanzas delay the revelation of the child. Public shame contrasts with maternal affection.','Victorian class, inheritance and sexual double standards explain unequal judgement. Her claims about Kate remain one speaker’s view.'),
p('Catrin: the idea','Clarke connects childbirth with a later argument over skating. The cord becomes a metaphor for continuing attachment.','Love and conflict coexist: mother and daughter seek separate identities without losing their bond.'),
p('Catrin: the method','Two unequal stanzas link past and present. Free verse and enjambment carry complicated feeling across boundaries.','Clinical squares contrast with emotional circles. Motherhood is voiced from lived experience; neither side simply wins.'),
p('Origin Story: the idea','Ewing recounts her parents’ meeting through a comic book, then uses fragile paper to explore their love.','A comic may be preserved or worn through use. An ended relationship can still leave value through the child.'),
p('Origin Story: the method','Two free-verse stanzas move from family narrative to reflection. Lists contrast protection with lived enjoyment.','Chicago and Black family experience give personal history significance. Compare Cousin Kate’s defiance with this affectionate reassessment.')]),
m('04-war-and-exclusion','War & exclusion',['A life ends abroad','A survivor is neglected','A return brings rejection'],[
p('Drummer Hodge: the idea','Hardy names a young drummer hurriedly buried without a coffin. He will become part of land he never understood.','Local landscape terms and strange stars separate him from Wessex. Natural continuity does not cancel loss.'),
p('Hodge: the method','Three six-line stanzas; alternating rhyme. Present burial → past home → permanent future.','Second Boer War, southern Africa. Ordinary loss challenges glamorous imperial war; it is not a First World War setting.'),
p('Disabled: the idea','Owen contrasts a veteran’s present dependence with sport, attraction and recruitment enthusiasm.','Colourful memory meets grey isolation. The public that celebrated enlistment offers little meaningful welcome.'),
p('Disabled: the method','Past/present shifts deny a simple heroic journey. Repeated final questioning leaves the man waiting.','First World War context exposes recruitment glamour and inadequate care. Analyse society’s treatment, not a claim about every disabled life.'),
p('Kamikaze: the idea','Garland’s returning pilot survives a suicide mission but is shunned. Sea life and childhood memories offer possible reasons for returning.','His daughter reconstructs his thoughts; the pilot never gives us his own account.'),
p('Kamikaze: the method','Seven six-line stanzas. Layered voices and fluid enjambment give way to learned silence at home.','Second World War military honour conflicts with family affection. Compare social rejection with Disabled and irreversible loss with Hodge.')]),
m('05-witnessing-and-trauma','Witnessing & trauma',['A participant remembers','A witness records','An observer reconsiders'],[
p('Remains: the idea','Armitage’s soldier recalls a shared shooting, then cannot escape it at home. Uncertainty about the man’s weapon persists.','The mark on the road becomes a mental presence. War imagery relocates the conflict inside his head.'),
p('Remains: the method','Colloquial dramatic monologue; enjambment drives the account. Shared pronouns narrow towards isolated responsibility; final couplet concentrates it.','Veterans’ testimony informed The Not Dead. The poetic speaker is not Armitage himself.'),
p('War Photographer: the idea','Duffy’s photographer develops film while painful memories return. A few published images receive a brief response.','Religious imagery makes his task solemn. Domestic safety contrasts with suffering he witnessed.'),
p('War Photographer: the method','Four sestets with ABBCDD rhyme impose order beside emotional disturbance. The ending resumes the work cycle.','Film darkroom and newspaper culture shape the ethical problem. Professional composure can coexist with distress.'),
p('Decomposition: the idea','Ghose’s speaker re-examines a photograph of a sleeping beggar in Bombay. Earlier pride becomes shame about turning hardship into art.','Stone imagery seems to erase individuality; the poem then challenges that way of seeing.'),
p('Decomposition: the method','Five quatrains in free verse. Past confidence changes to present self-criticism. The beggar is asleep, not confirmed dead.','Compare photographer, subject and viewer responsibilities. Duffy questions the audience; Ghose also questions the image-maker.')]),
m('06-home-and-belonging','Home & belonging',['Long for return','Find inward restoration','Face permanent separation'],[
p('I Shall Return: the idea','McKay’s speaker promises a return to cherished landscape, music and community. Precious colours make the remembered homeland valuable.','Final pain explains the need for belonging. Repetition expresses resolve and possible self-reassurance.'),
p('McKay: the method','A Shakespearean sonnet: three quatrains and a couplet. Nature → community → emotional explanation.','Jamaican migration and the Harlem Renaissance illuminate cultural attachment. The hoped-for return is not shown happening.'),
p('Compare Wordsworth','Both connect nature with emotional relief. Wordsworth’s remembered flowers already change his present mood.','McKay longs to be physically home. Compare **fulfilled recollection** with **future promise**, using each ending.'),
p('Compare Drummer Hodge','Both place identity in relation to a landscape. Hodge’s unfamiliar sky contrasts with McKay’s cherished colours and music.','Hodge cannot return. The landscape absorbs him after death; McKay imagines belonging through living participation.'),
p('Context changes meaning','Wordsworth: Romantic faith in imagination. McKay: separation from a homeland and culture. Hardy: an ordinary life displaced by imperial war.','Use these contexts to explain specific choices, not as detached biography.'),
p('Write a connected argument','Choose the pair that fits the question. Track time: remembered past → present effect → hoped-for or permanent future.','Compare language, form and structure as well as content. A shared natural setting does not prove shared emotions.')])]
for item,panel,kind,height in [(MAPS[0],5,'lit-camera',95),(MAPS[1],4,'lit-nature',95),(MAPS[2],4,'lit-absence',100),(MAPS[3],2,'lit-bond',90),(MAPS[4],4,'lit-return',100),(MAPS[5],2,'lit-camera',95),(MAPS[6],0,'lit-home',95)]:item['pics'][panel]=(kind,height)
