"""Original short recall and analysis practice for the two prepared Literature topics."""
from literature_qa_writer import q


def quick_bank(rows, topic):
    return [q(marks, prompt, answer,
              'Original quick-revision practice; teacher-assigned practice marks, not an Eduqas exam task. '
              + topic + '; factual/textual evidence checked against the primary text.')
            for marks, prompt, answer in rows]


def macbeth_quick():
    return quick_bank([
        (1, 'Who is King of Scotland when the play begins?', 'Duncan.'),
        (1, 'Which new title does Macbeth receive soon after meeting the witches?', 'Thane of Cawdor.'),
        (1, 'Whose descendants do the witches predict will become kings?', 'Banquo’s.'),
        (1, 'Who escapes when Banquo is murdered?', 'Fleance.'),
        (1, 'Who discovers Duncan’s body?', 'Macduff.'),
        (1, 'Who becomes king at the end of the play?', 'Malcolm.'),
        (1, 'Who describes his own motive as “vaulting ambition”?', 'Macbeth.'),
        (1, 'Who says “Out, damned spot”?', 'Lady Macbeth.'),
        (1, 'Which wood appears to move towards Dunsinane?', 'Birnam Wood.'),
        (1, 'Whose ghost does Macbeth see at the banquet?', 'Banquo’s.'),
        (1, 'Who kills Macbeth?', 'Macduff.'),
        (1, 'What is the term for a speech in which a character speaks private thoughts aloud, usually while alone?', 'Soliloquy.'),
        (1, 'What is the term for a situation in which the audience knows something a character does not?', 'Dramatic irony.'),
        (1, 'Complete Lady Macbeth’s image: look like the “innocent flower”, but be the what beneath it?', 'Serpent.'),
        (1, 'Does the audience see Duncan being murdered onstage?', 'No. The murder happens offstage.'),
        (2, 'Give two duties Macbeth has towards Duncan before the murder.',
         '- As Duncan’s **subject**, Macbeth owes him loyalty.\n- As Duncan’s **host**, Macbeth should protect him.\n\nHe is also Duncan’s relative, giving him a further reason to protect him.'),
        (2, 'What does “Stars, hide your fires” suggest about Macbeth’s desires?',
         '- He wants darkness to **conceal** his ambition.\n- Wanting to hide it suggests that he recognises it is **morally wrong**.'),
        (2, 'Explain the image “vaulting ambition”.',
         '- Ambition is compared to **leaping too far**, like a rider overshooting.\n- It suggests that excessive ambition can cause a **fall**, anticipating Macbeth’s destruction.'),
        (2, 'How does Lady Macbeth use Macbeth’s ideas about manhood to influence him?',
         '- “When you durst do it, then you were a man” makes murder a test of **masculinity**.\n- She pressures him to prove his courage instead of following his moral objections.'),
        (2, 'How do Macbeth’s “ocean” and Lady Macbeth’s “little water” present different responses to Duncan’s murder?',
         '- Macbeth imagines an entire ocean cannot remove his **guilt**.\n- Lady Macbeth treats it as a small, practical problem of washing away the **evidence**.'),
        (2, 'What does Macbeth mean by a “fruitless crown”?',
         '- He fears that his kingship will not produce a lasting **dynasty** for his family.\n- Banquo’s predicted descendants make the crown feel insecure and unfulfilling.'),
        (2, 'Explain one effect of “full of scorpions is my mind”.',
         '- The **metaphor** fills Macbeth’s mind with painful, poisonous creatures.\n- It makes his anxiety seem like torment from which he cannot escape.'),
        (2, 'How does the banquet scene expose the weakness of Macbeth’s authority?',
         '- His response to Banquo’s ghost makes him lose control in front of his guests.\n- The public display of fear undermines the appearance of a confident, secure king.'),
        (2, 'How does “Be innocent of the knowledge, dearest chuck” show a change in the Macbeths’ relationship?',
         '- Macbeth withholds the details of the murder plan from Lady Macbeth.\n- This contrasts with their earlier **partnership** and shows her growing exclusion.'),
        (2, 'Why is the attack on Macduff’s family important to the presentation of Macbeth?',
         '- It shows his violence targeting **innocent, vulnerable people**.\n- The audience sees the human cost of his **tyranny**, beyond his own fears.'),
        (2, 'What alternative view of masculinity does Macduff express in “I must also feel it as a man”?',
         '- Being a man includes feeling **grief and love**, not hiding them.\n- His response challenges the idea that courage requires emotional hardness.'),
        (2, 'How is the prophecy about Birnam Wood fulfilled?',
         '- Malcolm’s soldiers carry branches to **conceal their numbers**.\n- Their advance makes the wood appear to move towards Dunsinane.'),
        (2, 'Why does the promise about “none of woman born” fail to protect Macbeth from Macduff?',
         '- Macduff reveals that he was cut from his mother’s womb: “Untimely ripped”.\n- This fulfils the prophecy in a way Macbeth did not expect, exposing its **misleading reassurance**.'),
        (2, 'How does Lady Macbeth’s hand-rubbing connect with her earlier response to guilt?',
         '- It echoes her earlier claim that “A little water” could clear the deed.\n- Her inability to remove the imagined stain shows that **guilt cannot simply be washed away**.'),
        (2, 'What does “Life’s but a walking shadow” suggest about Macbeth near the end?',
         '- A shadow has little substance and does not last.\n- The **metaphor** expresses his feeling that life and his achievements have become empty.')
    ], 'Macbeth, Folger Shakespeare Library')


def poetry_quick():
    return quick_bank([
        (1, 'In The Schoolboy, what trapped creature is used to suggest the child’s lack of freedom?', 'A caged bird.'),
        (1, 'Which flowers does the speaker encounter in I Wandered Lonely as a Cloud?', 'Daffodils.'),
        (1, 'What happens to the collected fruit in Blackberry Picking?', 'It rots.'),
        (1, 'In Sonnet 29, the speaker’s thoughts are compared to vines. What does the tree represent?', 'The beloved.'),
        (1, 'What does the speaker reveal she has at the end of Cousin Kate?', 'A son.'),
        (1, 'Which family relationship is explored in Catrin?', 'Mother and daughter.'),
        (1, 'What is the speaker waiting for in Dusting the Phone?', 'A call from an absent lover.'),
        (1, 'Which war provides the setting for Drummer Hodge?', 'The Second Boer War.'),
        (1, 'Who wrote Disabled?', 'Wilfred Owen.'),
        (1, 'In Kamikaze, does the pilot return home from his mission?', 'Yes.'),
        (1, 'Where does the photographer develop the photographs in War Photographer?', 'A darkroom.'),
        (1, 'Does Remains establish for certain whether the man who is shot is armed?', 'No.'),
        (1, 'What poetic form does McKay use in I Shall Return?', 'A Shakespearean sonnet.'),
        (1, 'Is the photographed man in Decomposition described as asleep or dead?', 'Asleep.'),
        (1, 'What kind of book connects the parents’ meeting with the central imagery in Origin Story?', 'A comic book.'),
        (2, 'How does the caged-bird image develop Blake’s argument in The Schoolboy?',
         '- A cage prevents a bird from expressing its natural freedom and song.\n- The comparison suggests that fearful schooling restricts a child’s **joy and curiosity**.'),
        (2, 'How does the final stanza change the significance of the daffodils in I Wandered Lonely as a Cloud?',
         '- The speaker recalls them later while alone at home.\n- Nature becomes a lasting source of pleasure through **memory**, rather than only a momentary encounter.'),
        (2, 'What is the effect of the change between the two stanzas of Blackberry Picking?',
         '- Excited gathering gives way to the stored berries’ decay.\n- The contrast reveals the limits of trying to **preserve pleasure** and turns desire into disappointment.'),
        (2, 'How do the vines and tree develop the idea of longing in Sonnet 29?',
         '- The vines represent thoughts that grow around and obscure the beloved.\n- The speaker wants the real person’s **presence**, rather than imagination as a substitute.'),
        (2, 'How does the ending of Cousin Kate challenge the speaker’s apparent powerlessness?',
         '- She has a son who matters as a possible **heir**.\n- Her pride in him challenges the social judgement that treats her only as a disgraced woman.'),
        (2, 'How does the movement from childbirth to a later disagreement develop Catrin?',
         '- It links the struggle of physical separation at birth with a daughter’s later wish for **independence**.\n- Love remains, but the tension between attachment and freedom continues.'),
        (2, 'How does personifying the telephone develop the speaker’s feelings in Dusting the Phone?',
         '- The phone seems to demand attention and service, as if it could respond to the speaker’s efforts.\n- This reveals **dependence and anxiety**: waiting for contact dominates the speaker’s life.'),
        (2, 'Give two ways Hardy presents the loss of an ordinary soldier in Drummer Hodge.',
         '- The hurried burial without a coffin suggests a lack of personal care.\n- The unfamiliar foreign landscape makes his **permanent separation from home** clear.'),
        (2, 'How do shifts between past and present affect the reader in Disabled?',
         '- Memories of sport, attraction and public excitement contrast with present isolation.\n- This exposes the gap between the **promises of military life** and the neglect experienced afterwards.'),
        (2, 'How does Kamikaze present survival as more complicated than simply returning alive?',
         '- The pilot survives physically, but his family and community treat him as absent.\n- Their rejection makes survival a form of **social isolation**, challenging the value placed on military honour.'),
        (2, 'How does the controlled structure of War Photographer contrast with its subject?',
         '- Its regular stanzas and rhyme create a sense of **order**.\n- This contrasts with violent suffering and distress that the photographer cannot fully contain.'),
        (2, 'Why is uncertainty about the man’s weapon important in Remains?',
         '- It leaves the speaker unsure whether the shooting was justified.\n- The unresolved doubt returns in memory, contributing to lasting **guilt and distress**.'),
        (2, 'What can the repeated promise in the title I Shall Return suggest?',
         '- It expresses determination and hope of returning home.\n- Repetition can also sound like **self-reassurance**, revealing the pain beneath the confidence.'),
        (2, 'How does the speaker’s attitude to the photograph change in Decomposition?',
         '- The speaker moves from pride in a striking image towards questioning that pride.\n- This raises **ethical responsibility**: the subject is a person experiencing hardship, not just material for art.'),
        (2, 'How does the comic-book imagery help create the ending of Origin Story?',
         '- A worn comic can have value because it has been loved and used, rather than perfectly preserved.\n- Similarly, the parents’ relationship can end yet still create something worthwhile, including the speaker’s life.')
    ], 'Eduqas anthology for first assessment in 2027, all fifteen poems')
